### ISSUE TITLE
memory leak in gsad

### ISSUE THREAD

**Issue by pomac303** [greenbone/gsa#1056]
### Expected behavior

Running as a webservice, using a minimal amount of memory

### Actual behavior

It oom:s my server, just restarted it since it was using 4.9 GB of RES memory... 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                 
 2327 root      20   0 6189848 4,950g  10484 S   0,0 42,3  11:47.84 gsad                    

### Steps to reproduce

1. Start it
2. let it run
3. see it consume memory

Seriously though, do you have any clues or ideas of debugging and finding out?

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 7.0.3
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 5.1.3
Most new code since 2005: (C) 2016 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm-libs:**
9.0.3

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

Ubuntu 18.04

Packages, specially built manager to use postgres since sqlite doesn't scale...

### Logfiles

```
```

**Comment by tbiens** [comment]
I am having exactly the same issue. Happy to help investigate, I don't know how to go after memory leaks.

**Comment by pomac303** [comment]
You'd think that downloading a patch would be easy on github but no such luck... what am I missing?

**Comment by cfi-gb** [comment]
@pomac303 
> You'd think that downloading a patch would be easy on github but no such luck... what am I missing?

Not sure if there is any documentation on this available at the [github Help](https://help.github.com/) but from time to time a "ProTip!" is shown at the bottom of each PR which contains a note like (example of the #676 PR including the related links):

>  ProTip! Add [.patch](https://github.com/greenbone/gsa/pull/676.patch) or [.diff](https://github.com/greenbone/gsa/pull/676.diff) to the end of URLs for Git’s plaintext views.

**Comment by pomac303** [comment]
Ok, usually there is a "raw" or so link... 

Anyway, I applied it manual and while there still seems to be a memory leak it's much better

**Comment by pomac303** [comment]
VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
2104104 1,275g  10308 S   0,0 10,9   3:33.08 gsad 

I do tend to extract the CVE reports though, so I wonder if there is something there that isn't handled properly

**Comment by pomac303** [comment]
Took longer, still leaks quite a bit... 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                          
27997 root      20   0 5871424 4,161g   9680 S   0,0 35,5   8:57.16 gsad
