### ISSUE TITLE
ssh-login with key without passphrase protection fails

### ISSUE THREAD

**Issue by tps800** [greenbone/gsa#1104]
### Expected behavior
After importing ssh-keys, authenticated checks shall work

### Actual behavior
ssh-login with key without passphrase protection fails

### Steps to reproduce
1. Install gvm, configure, then create some authenticated checks
2. Test if ssh-key works as expected, by logging into the system from your scanning system
3. Start scanning some clients you could successfully login remote using ssh

### GVM Versions
Oops, secure memory pool already initialized
**gsad:**
```
99123d763 2018-12-17 | Don't reject promise if no setting is available (HEAD -> master, origin/master, origin/HEAD)

Greenbone Security Assistant 8.0+beta3
GIT revision 99123d763-master
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**gvmd:**
```
01a99ee2 2018-12-18 | Merge pull request #291 from timopollmeier/credential-private-key-fix (HEAD -> master, origin/master, origin/HEAD)

Greenbone Vulnerability Manager 8.0+beta2
GIT revision 01a99ee2-master
Manager DB revision 200
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**openvassd:**
```
b1d4ca6 2018-12-14 | Merge pull request #231 from jjnicola/vendor-ua (HEAD -> master, origin/master, origin/HEAD)

OpenVAS Scanner 6.0+beta3
GIT revision b1d4ca6-master
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**gvm-libs:**
```
b271a6cf 2018-12-13 | Merge pull request #161 from greenbone/davidak-patch-1 (HEAD -> master, origin/master, origin/HEAD)
```

**gvm-tools:**
```
bb98ebd 2018-10-30 | Merge pull request #120 from jjnicola/delete-methods (HEAD -> master)
```

**node:**
```
v11.5.0
```

**redis-server:**
```
Redis server v=5.0.2 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=669dbd6bdc6d120c
```

### Environment
**Operating system**:
```
Linux gvm10 4.18.0-3-amd64 #1 SMP Debian 4.18.20-2 (2018-11-23) x86_64 GNU/Linux
```
```
Debian testing (buster/sid)
```

**Installation method / source:**
```
source installation, git checkout
```

### Logfiles
Nothing found within.

**Comment by cfi-gb** [comment]
Hi,

this is not necessarily an issue of the GSA as it only provides the uploaded credentials to other components like manager (openvasmd/gvmd) or scanner (openvassd). Other factors (like SSH target configuration, libssh version on the scanning system etc.) plays a role as well (see e.g. https://github.com/greenbone/openvas-scanner/issues/68, or specially https://github.com/greenbone/openvas-scanner/issues/68#issuecomment-405186050).

The VT mentioned in https://github.com/greenbone/openvas-scanner/issues/68#issuecomment-384953934 might give you some additional hints on this topic.
