### ISSUE TITLE
scanner -  loses the previous setting

### ISSUE THREAD

**Issue by dgiorgio** [greenbone/gsa#1112]
### Expected behavior
remember setting

### Actual behavior
ex: edit openvas-sshvpn, or any other scanner
![image](https://user-images.githubusercontent.com/17960988/50457283-8cb97780-0941-11e9-8224-c7736fd6c4cd.png)

loads the default setting, and loses the previous setting.
host: openvas-sshvpn -> localhost
port: 19390 -> 9391
![image](https://user-images.githubusercontent.com/17960988/50457316-b4104480-0941-11e9-9ef5-f650a95d06d3.png)

### Steps to reproduce

1. create a scanner
2. edit scanner 
3. 

### GVM versions

**gsa:** (gsad --version)
```
# gsad --version
Greenbone Security Assistant 8.0+beta3
GIT revision 99123d763-master
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**gvm:** (gvmd --version)
```
# gvmd --version
Greenbone Vulnerability Manager 8.0+beta2
GIT revision 01a99ee2-master
Manager DB revision 200
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**openvas-scanner:** (openvassd --version)
```
# openvassd --version
OpenVAS Scanner 6.0+beta3
GIT revision b1d4ca6-master
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**gvm-libs:**
git - checkout: b271a6cf76c938b938574a4fc7d862efe88c3239

### Environment

**Operating system:**

```
# cat /etc/debian_version
9.6
```
https://cloud.docker.com/u/dgiorgio/repository/docker/dgiorgio/openvas-source
tag: master-2.3

**Installation method / source:** (packages, source installation)

### Logfiles
OK
`event scanner:MESSAGE:2018-12-26 19h02.26 -02:4994: Scanner openvas-sshvpn (926355af-0df2-43a7-bbfa-74601b3ca539) has been modified by admin`

```
```

**Comment by bjoernricks** [comment]
Could you pleas re-test with current releases?

**Comment by dgiorgio** [comment]
ok, but before I need to recreate the environment, I do in the coming weeks.
