### ISSUE TITLE
Creating New Alert error: "Given filter_id was invalid"

### ISSUE THREAD

**Issue by pyron83** [greenbone/gsa#1136]
### Expected behavior
Creating a New Alert without error with default options.
I tried various settings but when I click "save" the error "Given filter_id was invalid" is showed.
NB: i'm pretty sure this issue was absent some weeks ago when I began the first tests with GVM10, but I don't remember which git version was.

### Steps to reproduce
Create a New Alert, and press Save button.

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 8.0+beta3
GIT revision 29acdd6e5-master

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta2
GIT revision 6e48194f-master

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0+beta3
GIT revision 6f209c9-master

**gvm-libs:**
gvm-libs 1.0+beta2 (2018-12-04)

### Environment

**Operating system:**
Debian 9.6

**Installation method / source:** (packages, source installation)
git source installation

### Logfiles
no logs in gsa.log
```
```

**Comment by bjoernricks** [comment]
I am really sure this got fixed today with https://github.com/greenbone/gsa/pull/1132

**Comment by pyron83** [comment]
I confirm the resolution, just did a git pull and a make install and then created a test alert, now it works. thanks
