### ISSUE TITLE
GSA 9.0 users list is empty

### ISSUE THREAD

**Issue by M1chael** [greenbone/gsa#1175]
### Expected behavior

`https://<GSAinstance>/users` should list avaliable users

### Actual behavior

![No Users avaliable](https://user-images.githubusercontent.com/920901/52518594-83c10300-2c6e-11e9-92c7-43f81ee10008.png)

### Steps to reproduce

1. create user with `gvmd --create-user=adminuser --role=Admin`
2. login to GSA with "adminuser"
3. goto https://<GSAinstance>/users and see the «No Users avaliable»
4. create user "realadmin" with GSA
5. relogin to GSA with "realadmin
6. goto https://<GSAinstance>/users and see the «No Users avaliable»

### GVM versions

**gsa:** 9.0+alpha~git-7d75f9f24-master

**gvm:** 8.0+beta3

**openvas-scanner:** 6.0+beta3

**gvm-libs:** gvm-libs 1.0.0

### Environment

**Operating system:** Debian 9

**Installation method / source:** source installation

### Logfiles

```
$ gvmd --get-users
adminuser
realadmin
```

**Comment by bjoernricks** [comment]
gvmd --get-users is not the same as the users list in gsa. gsa only shows users the the current user has access to. You have to adjust the permissions. gvmd --get-users query the db and gsa(d) talks via gmp to gvmd.

**Comment by M1chael** [comment]
> gvmd --get-users is not the same as the users list in gsa. gsa only shows users the the current user has access to. gvmd --get-users query the db and gsa(d) talks via gmp to gvmd.

Yep, sure. Thanks for the reminder.

> You have to adjust the permissions. 

A user with _admin role_ doesn't see even _itself_ in the user list. Is it an acceptable user management flow?

**Comment by bjoernricks** [comment]
> A user with _admin role_ doesn't see even _itself_ in the user list. Is it an acceptable user management flow?

Personally I just did ran into this problem two weeks ago and was wondering too.  We had a short discussion and agreed on changing this behavior in future.

**Comment by bjoernricks** [comment]
Should be fixed with https://github.com/greenbone/gvmd/pull/424
