### ISSUE TITLE
[8.0.0] build fails with missing include

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#1258]
OS: CentOS 7.6
/usr/bin/cmake3 -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr
 -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DSYSCONFDIR=/etc -DG
VM_LOG_DIR=/var/log/greenbone/gsa -DGVM_STATE_DIR=/var/lib/greenbone -DGVM_CA_CERTIFICATE=/etc/pki/tls/cert.pem -DGVM_SERVER_KEY=/etc/pki/tls/private/gsa -DGVM_SERVER_CERTIFICATE=/etc/pki/tls/certs/gsa -DYARN_OF
FLINE=True -DCMAKE_LIBRARY_PATH:PATH=/usr/lib64/gvm-helper .
-- Configuring Greenbone Security Assistant...
-- The C compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/lib64/ccache/cc
-- Check for working C compiler: /usr/lib64/ccache/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Looking for clang-format...
-- Looking for clang-format... /usr/bin/clang-format
-- Install prefix: /usr
-- Found Node: /opt/rh/rh-nodejs10/root/usr/bin/node (found suitable version "10.10.0", minimum required is "8.0") 
-- Found Yarn: /usr/bin/yarn (found suitable version "1.15.2", minimum required is "1.0") 
-- Found Yarn: /usr/bin/yarn
-- Using Yarn in offline mode
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Found PY_polib: /usr/lib/python2.7/site-packages/polib.pyc  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Checking for module 'libmicrohttpd>=0.9.0'
--   Found libmicrohttpd, version 0.9.63
-- Checking for module 'libxml-2.0'
--   Found libxml-2.0, version 2.9.1
-- Checking for module 'glib-2.0>=2.42'
--   Found glib-2.0, version 2.56.1
-- Checking for module 'libgvm_base>=10.0.0'
--   Found libgvm_base, version 10.0.0
-- Checking for module 'libgvm_util>=10.0.0'
--   Found libgvm_util, version 10.0.0
-- Checking for module 'libgvm_gmp>=10.0.0'
--   Found libgvm_gmp, version 10.0.0
-- Checking for module 'gnutls>=3.2.15'
-   Found gnutls, version 3.3.29
-- Looking for libgcrypt...
-- Looking for libgcrypt... /usr/lib64/gvm-helper/libgcrypt.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot 
-- Looking for xmltoman...
-- Looking for xmltoman... /usr/bin/xmltoman
-- Looking for xmlmantohtml... /usr/bin/xmlmantohtml
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_CXX_FLAGS_RELEASE
    CMAKE_Fortran_FLAGS_RELEASE
    INCLUDE_INSTALL_DIR
    LIB_INSTALL_DIR
    LIB_SUFFIX
    SHARE_INSTALL_PREFIX
    SYSCONF_INSTALL_DIR
-- Build files have been written to: /builddir/build/BUILD/gsa-8.0.0
+ make -j16
....
/builddir/build/BUILD/gsa-8.0.0/gsad/src/gsad.c:92:25: fatal error: gitrevision.h: No such file or directory
 #include "gitrevision.h"

**Comment by tuxmaster5000** [comment]
I have used the tar ball, not the git checkout.

**Comment by blshkv** [comment]
gvmd is also affected: https://github.com/greenbone/gvmd/blob/master/src/gvmd.c#L107
