### ISSUE TITLE
Report Composer doesn't open

### ISSUE THREAD

**Issue by Chartman123** [greenbone/gsa#1276]
### Expected behavior

When clicking on the Compose button in the Edit Alert Window, the Report Composer should open.

### Actual behavior

Nothing happens. (see attached logfile)

### Steps to reproduce

1. Go to Configurations - Alerts
2. Click on Edit button for an alert
3. Click on Compose button

### GVM versions

**gsa:** 9.0+alpha (basically 8.0.0, just used a check-out from master because build failed with 8.0.0, https://github.com/greenbone/gsa/issues/1258)

**gvm:** 8.0.0

**openvas-scanner:** 6.0.0

**gvm-libs:** 10.0.0

### Environment

**Operating system:** Linux mak1-vas1 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

**Installation method / source:** source

### Logfiles

[mak1-vas1.sgr.lan-1555069351649.log](https://github.com/greenbone/gsa/files/3073103/mak1-vas1.sgr.lan-1555069351649.log)

**Comment by bjoernricks** [comment]
Fixed in #1280
