### ISSUE TITLE
[8.0.0] Unable to alter ssh credentials  where the user name contains an hyphen

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#1346]
### Expected behavior

That I can alter login credentials, where the login can have an hyphen in it.

### Actual behavior
I get this error:
![Bildschirmfoto von 2019-05-02 13-55-10](https://user-images.githubusercontent.com/837503/57073673-0394c180-6ce2-11e9-9ce1-3bd003f6752e.png)

But when I create an new credentials, then foo-bar are possible as the login name.

### Steps to reproduce
Simple alter credentials.

### GVM versions

**gsa:** (gsad --version)
8.0.0~git

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0.0
Manager DB revision 205

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0.0

**gvm-libs:**
10.0.0

### Environment

**Operating system:**
CentOS 7.6

**Installation method / source:**
From git

**Comment by y0urself** [comment]
Please recreate/reopen if still relevant in latest version(s).
