### ISSUE TITLE
[7.0.3] Stored filter is not recalled correctly on Results view

### ISSUE THREAD

**Issue by uwedisch** [greenbone/gsa#1363]
Hello,

if the filter "apply_overrides=1 min_qod=70 autofp=0 levels=hml first=1 rows=50 sort-reverse=created not tag~result" of issue #1362 is stored and later on recalled, then the total number of findings isn't calculated correctly. In #1362 we have determined a total of 46 when the filter is applied.

See screenshot:

![Bildschirmfoto vom 2019-05-04 08-22-57](https://user-images.githubusercontent.com/24267159/57175015-415f2a80-6e47-11e9-870e-c86f112581b6.png)

Quick test shows, that the filter part "not tag~result" is destroying the filter part "levels=hml" on the charts. But only with stored filters, not after a filter reload (see issue #1362).

This is GSA 7.0.3 on Kali rolling.

**Comment by bjoernricks** [comment]
Hi, could you please check if this issue is still valid for GVM 10 with GSA 8? It's very likely that this issue wont get fixed in GSA 7 anymore.

**Comment by uwedisch** [comment]
I have currently no chance testing it with GSA 8.

Do you have possibility to test this simple case with GSA 8?

**Comment by bjoernricks** [comment]
Can't promise. I'll try to take a look.

**Comment by bjoernricks** [comment]
OpenVAS/GVM 9 is end of life. Therefore I am closing this issue.
