### ISSUE TITLE
--version argument should only print the version

### ISSUE THREAD

**Issue by davidak** [greenbone/gsa#1375]
Would you accept a PR with this change?

This would also clean up future bugreports.

### Expected behavior

I expect to get just the version number.

Like with other tools:

```
$ git --version
git version 2.19.2

$ man --version
man 2.7.5

$ chromium --version
Chromium 74.0.3729.108
```

### Actual behavior

```
root@gsm:~# gsad --version
Oops, secure memory pool already initialized
Greenbone Security Assistant 8.0.0
Copyright (C) 2010 - 2019 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I also get a bunch of other information not related to the command.

### Steps to reproduce

1. `gsad --version`

### GVM versions

**gsa:** 8.0.0

**gvm:** 8.0.0

**openvas-scanner:** 6.0.0

**gvm-libs:**

### Environment

**Operating system:** GOS 5

**Comment by bjoernricks** [comment]
You are right this is much to verbose currently.
