### ISSUE TITLE
Replace dialogcontainer component

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#14]
ng contains some old concept of DialogContainers. These container components have been implemented to not having to implement save and create handler several time. But as time goes by this DialogContainer concept has been made obsolete.

Currently there are still

./src/web/components/dialog/container.js
./src/web/pages/targets/dialogcontainer.js
./src/web/pages/tasks/dialogcontainer.js
./src/web/pages/alerts/dialogcontainer.js

They should be replaced with a SaveDialog component in combination with a EntityComponent (e.g. TaskComponent).

**Comment by swaterkamp** [comment]
Update
There seem to be only these containers left:

./src/web/components/dialog/container.js
./src/web/pages/tasks/dialogcontainer.js
