### ISSUE TITLE
[8.0.0] password's not masked in the log file on debug mode

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#1408]
### Expected behavior
That password are filtered out in the log file with "***masked***" or something like that.

### Actual behavior

The login password is logged full into the log file. 

### Steps to reproduce
1. set debug mode for logging
2. restart gsa
### GVM versions

**gsa:** (gsad --version)
8.0.0

### Environment

**Operating system:**
CentOS 7.6

**Installation method / source:** 
8.0.0 from guthub

I think passwords should never be visible in log files.

**Comment by bjoernricks** [comment]
Could you show me the log output (of course without password)? It's easier to find the corresponding code line when having the exact output.

**Comment by tuxmaster5000** [comment]
dummpypw was the phantasy's password

> gsad vali:  DEBUG:2019-05-16 06h49.12 utc:7785: gvm_validate: name password value dummpypw
> gsad vali:  DEBUG:2019-05-16 06h49.12 utc:7785: matching <^.*$> against <dummpypw>:

**Comment by bjoernricks** [comment]
It's logged due to enabled debugging for the http parameter validation. The validation part is really generic and should not be enabled under normal circumstances. So I don't think adding extra logic here for not displaying the password is worth the afford.

**Comment by bjoernricks** [comment]
I am closing this issue because enabling debug log for the parameter validation should not be done on a production server.
