### ISSUE TITLE
[8.0.0] Unable to add permissions to an role

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#1411]
### Expected behavior

That the selected permission is added to the role.

### Actual behavior

"Given subject_type was invalid" error is shown after click on "Create Permission"
![rights](https://user-images.githubusercontent.com/837503/57840213-79138e00-77c8-11e9-9ffe-a6c0873deeb9.png)

### Steps to reproduce

1.  Create an new empty role
2.  Try to add permissions

### GVM versions

**gsa:** (gsad --version)
8.0.0

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0.0

### Environment

**Operating system:**
CentOS 7.6

### Logfiles
Nothing was logged on log level 127.

**Comment by bjoernricks** [comment]
Should be fixed already with https://github.com/greenbone/gsa/pull/1365

**Comment by tuxmaster5000** [comment]
Yes, it will fix it.
Thanks.
