### ISSUE TITLE
Can not export report to PDF 

### ISSUE THREAD

**Issue by jessie4736** [greenbone/gsa#1436]
when export report format in pdf, downloaded still xml.

**Comment by cfi-gb** [comment]
@jessie4736 Please try to fill out the issue template (i'm pasting it below) which is shown when creating a new issue in this bugtracker.

Without this information it is impossible to help and the issue is very likely to be closed due to the lack of information provided.

```
<!--
If reporting an issue please try to provide the information asked below.

Before reporting an issue please:

1. Be aware that this is not a support forum. If your issue is rather a question
   than a bug report, please use our community forum at
   https://community.greenbone.net/c/gse instead.
2. Make sure that you're using the latest published GVM components for the
   release you are using: https://community.greenbone.net/t/about-the-source-edition-gse-category/176
3. Check the list of issues whether it isn't already reported.
4. Read 1. again and if you still believe you found a software bug please
   continue to file this issue. If you are in doubt use
   https://community.greenbone.net/c/gse instead.

Thanks for your help to keep the communication channels clean and consistent!
-->

### Expected behavior

<!--
  How did you expect GSA to behave?
  Please write down how the web interface should work in your opinion.
-->

### Actual behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Is this really an bug? If in doubt please use
  https://community.greenbone.net/c/gse instead.
  Please attach screenshots if possible! They are extremely helpful for
  diagnosing issues.
-->

### Steps to reproduce

<!--
  How would you describe your issue to someone who doesn’t know GSA?
  Try to write a sequence of steps that anybody can repeat to see the issue.
-->

1.
2.
3.

### GVM versions

**gsa:** (gsad --version)

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

### Environment

**Operating system:**

<!-- e.g. paste output of uname -a and cat /etc/lsb-release -->

**Installation method / source:** (packages, source installation)

### Logfiles

<!-- in most cases you'll find the logs in /var/log/gvm/ -->
```

**Comment by jessie4736** [comment]
### Expected behavior

scan and export report.

### Actual behavior

install to centos7 following the link:
https://www.linuxincluded.com/installing-openvas-on-centos-7/

### Steps to reproduce

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 8.0.0
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0.0
Manager DB revision 205
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0.0
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**gvm-libs:**

### Environment

**Operating system:**

Linux XXXXXXX 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** (packages, source installation)

### Logfiles

nothing wrong

**Comment by bjoernricks** [comment]
@jessie4736 did you follow the *Configuring PDF Reports* section at https://www.linuxincluded.com/installing-openvas-on-centos-7/ ?

We need a details instruction to be able to reproduce your issue. Which GSA page did you use to download the pdf and which icon did you click. There are several possibilities to download a report.

**Comment by jessie4736** [comment]
@bjoernricks
yes, i follow the Configuring PDF Reports section at https://www.linuxincluded.com/installing-openvas-on-centos-7/ 

but still not work

**Comment by bjoernricks** [comment]
> but still not work

And we still need a detailed description what you are trying to do.

**Comment by gobind-singh** [comment]
@jessie4736, I was also not able to generate pdf reports. Resolved the issue after installing few packages specified below.
    - texlive-latex-recommended
    - texlive-latex-base
    - texlive-fonts-recommended
    - xsltproc
    - texlive-latex-extra

**Comment by bjoernricks** [comment]
@gobind-singh please let us know which distro in which version you did use and where you did the packages from. Also it would be good to let the distro packagers know about these missing dependencies.

**Comment by gobind-singh** [comment]
@bjoernricks actually i compiled it from source code and was not able to generate the pdf reports. Then after struggling a lot with this issue figured out the prerequisites required for generating pdf reports and came to a conclusion that the packages i mentioned previously are required.
os versions which i used: ubuntu16.04 and ubuntu18.04 
package manager: apt

**Comment by bjoernricks** [comment]
These requirements are listed here https://github.com/greenbone/gvmd/blob/master/INSTALL.md#prerequisites-for-optional-features too

**Comment by gobind-singh** [comment]
texlive-latex-base is not mentioned

**Comment by cfi-gb** [comment]
https://packages.debian.org/buster/texlive-latex-extra:
https://packages.debian.org/sid/texlive-latex-extra:

```
dep: texlive-base (>= 2018.20190227)
    TeX Live: Essential programs and files 
```

This is a hard dependency and will be always installed if you install the "texlive-latex-extra" prerequisite.

**Comment by bjoernricks** [comment]
> This is a hard dependency and will be always installed if you install the "texlive-latex-extra" prerequisite correctly.

exactly

**Comment by gobind-singh** [comment]
> These requirements are listed here https://github.com/greenbone/gvmd/blob/master/INSTALL.md#prerequisites-for-optional-features too

In prerequisites for generating PDF reports: xsltproc package is also needed. Please confirm
