### ISSUE TITLE
Content-Security-Policy prevents Cloudflare rocket loader to be used with GSA

### ISSUE THREAD

**Issue by ciphermenial** [greenbone/gsa#1440]
### Expected behavior
Load up GSA with Cloudflare Rocket Loader enabled.

### Actual behavior
Loads a blank screen and Firefox console reports: Content-Security-Policy prevents Cloudflare rocket loader to be used with...

### Steps to reproduce
1. Enable Cloudflare Rocket Loader
2. Browse to GSA

### GVM versions
**gsa:** 8.0.0
**gvm:** 8.0.0
**openvas-scanner:** 6.0.0

### Environment

**Operating system:** Ubuntu 18.04.2 LTS

**Installation method / source:** http://ppa.launchpad.net/mrazavi/gvm/ubuntu

FreshRSS have an issue logged for the same problem. https://github.com/FreshRSS/FreshRSS/issues/1681

**Comment by cfi-gb** [comment]
The gsad daemon has the following configuration option which you could modify to make it to work with Cloudflare rocket loader:

```
  --http-csp=<csp>                       Content-Security-Policy HTTP header.  Defaults to "default-src 'self' 'unsafe-inline'; img-src 'self' blob:; frame-ancestors 'self'".
```
