### ISSUE TITLE
Fix layout of action icons

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#16]
Several action icons (in lists and page toolbars) don't have a margin between them currently. They should be put into an IconDivider.

**Comment by bjoernricks** [comment]
Is this issue fixed with #119 ?

**Comment by swaterkamp** [comment]
Yes and no. Icons in the Action column of tables are fixed. The Icons in the toolbars are not. They are on my To-Do for today though. Missing dividers for: roles, groups, and port lists.
