### ISSUE TITLE
Task filter does not allow changing page

### ISSUE THREAD

**Issue by Fabi153** [greenbone/gsa#1639]
### Actual behavior

Hi, I created a task filter with qod_min=30 and applied it as default in the settings.
As a result, in the task overview, the filter automatically gets applied but I'm not able any more to navigate to page 2 or further.

### Steps to reproduce

1. Select Configuration -> Filters
2. Create new Task Filter with "min_qod=30"
3. Click Save
4. The newly crated filter appears, but with "min_qod=30 rows=10 sort=name first=1" (Why?)
5. Select Extras -> "My Settings"
6. Set the created filter as tasks filter
7. Go to Scans -> Tasks and try to navigate to page 2. 

I think this problem occurs due to the "rows=10". But why is this added automatically?

### GVM versions

**gsa:** Greenbone Security Assistant 8.0.0

**gvm:** Greenbone Vulnerability Manager 8.0.0

```
```

**Comment by bjoernricks** [comment]
Hi,

it is very likely that this issue is already fixed with the 8.0.1 release. Therefore I am closing this issue for now. Please re-open if I am wrong.
