### ISSUE TITLE
Empty download report

### ISSUE THREAD

**Issue by c0r3dump3d** [greenbone/gsa#1645]
### Expected behavior

Download report in any format (csv, pdf, tex) 

### Actual behavior

When I try to download a scan report in any format (CSV, PDF, TEX ...) the report is empty. 

### Steps to reproduce

1. Login GSA
2. Click Scan/Reports
3. Select a Report
4. Select download icon
5. Select PDF or CSV or TEX format
6. Generate and download the report
7. The report is empty

### GVM versions

**gvm:** (gvmd --version)
```
 gsad --version
Oops, secure memory pool already initialized
Greenbone Security Assistant 8.0.1
Copyright (C) 2010 - 2019 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
```

**gvm:** (gvmd --version)

```
# gvmd --version
Greenbone Vulnerability Manager 8.0.1
**openvas-scanner:** (openvassd --version)

```
**gvm-libs:**
v10.0.1
### Environment

**Operating system:**
```
# uname -a
Linux openvasserver 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux
```
```
# cat /etc/issue
Debian GNU/Linux 10 \n \l
```

**Installation method / source:**  source installation

### Logfiles

No erros in logs

I have installed some dependences to generate pdf and latex reports like: texlive-latex-recommended package.

**Comment by anonymous0871** [comment]
Solved! Iinstalled  xsltproc on my Ubuntu.
Now works like a charme.
Thank you

**Comment by c0r3dump3d** [comment]
Nice!!!
# apt install  xsltproc

Thank you very much
