### ISSUE TITLE
Reports show this.hosts is undefined

### ISSUE THREAD

**Issue by falkowich** [greenbone/gsa#1647]
### Expected behavior

Show a report from a scanned task.
The results of the scan is expected to be shown

### Actual behavior

Loading a long time, then "this.hosts is undefined" shows up.

![scrot-2019-09-28_20-55-25](https://user-images.githubusercontent.com/1552705/65821167-52636a80-e232-11e9-8ea9-d8ea5c928feb.png)

### Steps to reproduce

1. Install clean src from git versions below. 
2. Create a scan on whatever you want.
3. Wait until scan is populated with a result.
4. Navigate to: Scans » Tasks » Last Report

But if you navigate to Scans » Results. All the results are there

### GVM versions

**gsa:**   
Greenbone Security Assistant 8.0.2~git-78cde325b-gsa-8.0  

**gvm:**  
Greenbone Vulnerability Manager 8.0.2  
GIT revision 9471c263-gvmd-8.0  

**openvas-scanner:**   
OpenVAS Scanner 6.0.1  
GIT revision 80cf12f-openvas-scanner-6.0

**gvm-libs:**  
gvm-libs 10.0.1 (CHANGES)
GIT revision 109a983-gvm-libs-10.0

### Environment

**Operating system:**  
Linux scanner 4.15.0-64-generic #73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Installation method / source:** 
source and docker-image

### Logfiles

Nothing that points to this problem, what I can see..  
When debugging gvmd it seems like the xml is created but then things gets broken.

**Comment by bjoernricks** [comment]
Should be fixed already in gsa-8.0 and gsa-9.0 branches. Please re-open if the error still occurs.
