### ISSUE TITLE
[9.0.0] Unable to enable ldap

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#1707]
I can configure it, set the hook on enable and safe it.
But after it, Enabled jump to no. The configuration was saved.

But ldap login still works, so I think the correct value are not received.
Also I will be unable to add new ldap users, because the option (LDAP user) is missing in the new user form.

So exits ldap user can login via ldap auth, but it is impossible to add new one.
Run gsa in debug mode, it looks like the values are delivered correct from gvmd.

> 
> lib   xml:  DEBUG:2019-10-22 09h41.56 CEST:22903: <= <describe_auth_response status="200" status_text="OK"><group name="method:file"><auth_conf_setting><key>enable</key><value>true</value></auth_conf_setting><au
> th_conf_setting><key>order</key><value>1</value></auth_conf_setting></group><group name="method:ldap_connect"><auth_conf_setting><key>enable</key><value>true</value></auth_conf_setting><auth_conf_setting><key>or
> der</key><value>0</value></auth_conf_setting><auth_conf_setting><key>ldaphost</key><value>XXX</value></auth_conf_setting><auth_conf_setting><key>authdn</key><value>XXX</value></auth_conf_set
> ting><auth_conf_setting><key>allow-plaintext</key><value>0</value></auth_conf_setting><auth_conf_setting><key>cacert</key><value>XXX....
>

**Comment by swaterkamp** [comment]
Hi @tuxmaster5000,
thanks for reporting. @saberlynx fixed this with https://github.com/greenbone/gsa/pull/1723.
Enabling LDAP via the GUI should now be possible for you again.

**Comment by warschauer** [comment]
Hi @swaterkamp ,
no further issues have been reported on that? I recently installed from 9.0.0 and the 'Enabled' button doesn't seem to respond. Interestingly enough the ldap_enable value in the 'meta' table in the database changes.
