### ISSUE TITLE
New slider component

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#19]
The old version (gsa 7.0) has a slider component based on jquery. This component hasn't been used by intention in ng. We should implement/find a suitable slider component base on react for ng.

Hint: if I remember correctly the slider component is used for setting the min qod in the powerfilter dialogs.

**Comment by swaterkamp** [comment]
I don't think this component is really needed. It's relatively speaking quite the effort to implement it, while precisely setting the QoD via a Spinner (as it is done atm) is much easier, and it was used for QoD only in the past. It adds just another kind of input fiddling with UX for a single use-case.
I'd suggest closing this issue (also to clean up the issues list a bit).

**Comment by bjoernricks** [comment]
Done
