### ISSUE TITLE
overrides not applied

### ISSUE THREAD

**Issue by root360-AndreasUlm** [greenbone/gsa#2043]
Hi,

in our fresh installed GVM-11 we have some issue concerning the overrides not being applied to reports and downloads although filter 'apply_overrides=1' is set.

### Expected behavior

When applying overrides the matching results should be changed according to the overrides.

### Actual behavior

Results are shown although an override reducing severity applies ![image](https://user-images.githubusercontent.com/17042256/76434057-75837000-63b5-11ea-917f-c6587a555d71.png)
   * solution described on https://community.greenbone.net/t/override-s-not-taken-into-account-in-gvm-11/4362 failed, see screenshot

### Steps to reproduce

1. install and build main components (except OSPD) of [GVM-11](https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674) including requirements (e.g. postgresql & redis)
2. start all GVM daemons
    * gvmd: `gvmd --osp-vt-update=/var/run/ospd/ospd.sock --unix-socket /var/run/gvm/gvmd.sock`
    * ospd-openvas: `/usr/bin/ospd-scanner/bin/python /usr/bin/ospd-scanner/bin/ospd-openvas --pid-file /var/run/ospd/ospd-openvas.pid --unix-socket=/var/run/ospd/ospd.sock --log-file /var/log/gvm/ospd-scanner.log`
    * gsad: `gsad --drop-privileges=gvm --listen=127.0.0.1 --port=8443 --no-redirect --gnutls-priorities=SECURE128:-AES-128-CBC:-CAMELLIA-128-CBC:-VERS-SSL3.0:-VERS-TLS1.0:-VERS-TLS1.1 --munix-socket=/var/run/gvm/gvmd.sock --secure-cookie`
3. configure a security issue e.g.
    1. install nginx
    2. configure with insecure cookie:
```
server {
    listen 80;
    add_header Set-Cookie bla="bla";
    return 200;
}
```
4. run scan against vulnerable nginx
5. configure override for found vulnerability `Missing httpOnly Cookie Attribute OID: 1.3.6.1.4.1.25623.1.0.105925`
6. open scan report with `apply_override=1`
7. download report with `apply_override=1`

### GVM versions

**gsa:** (gsad --version)
```
# gsad --version
Greenbone Security Assistant 9.0
```

**gvm:** (gvmd --version)
```
# gvmd --version
Greenbone Vulnerability Manager 9.0.0
Manager DB revision 221
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**openvas-scanner:** (openvassd --version)
```
# openvas --version
OpenVAS 7.0.0
Most new code since 2005: (C) 2019 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

**gvm-libs:**
```
# ls -l /usr/lib/libgvm*
lrwxrwxrwx 1 root root     21 Mar 12 18:06 /usr/lib/libgvm-pg-server.so -> libgvm-pg-server.so.0
lrwxrwxrwx 1 root root     25 Mar 12 18:06 /usr/lib/libgvm-pg-server.so.0 -> libgvm-pg-server.so.9.0.0
-rw-r--r-- 1 root root  96816 Mar 12 18:06 /usr/lib/libgvm-pg-server.so.9.0.0
lrwxrwxrwx 1 root root     17 Mar 12 18:06 /usr/lib/libgvm_base.so -> libgvm_base.so.11
lrwxrwxrwx 1 root root     21 Mar 12 18:06 /usr/lib/libgvm_base.so.11 -> libgvm_base.so.11.0.0
-rw-r--r-- 1 root root 202160 Mar 12 18:06 /usr/lib/libgvm_base.so.11.0.0
lrwxrwxrwx 1 root root     16 Mar 12 18:06 /usr/lib/libgvm_gmp.so -> libgvm_gmp.so.11
lrwxrwxrwx 1 root root     20 Mar 12 18:06 /usr/lib/libgvm_gmp.so.11 -> libgvm_gmp.so.11.0.0
-rw-r--r-- 1 root root  58208 Mar 12 18:06 /usr/lib/libgvm_gmp.so.11.0.0
lrwxrwxrwx 1 root root     16 Mar 12 18:06 /usr/lib/libgvm_osp.so -> libgvm_osp.so.11
lrwxrwxrwx 1 root root     20 Mar 12 18:06 /usr/lib/libgvm_osp.so.11 -> libgvm_osp.so.11.0.0
-rw-r--r-- 1 root root  53472 Mar 12 18:06 /usr/lib/libgvm_osp.so.11.0.0
lrwxrwxrwx 1 root root     17 Mar 12 18:06 /usr/lib/libgvm_util.so -> libgvm_util.so.11
lrwxrwxrwx 1 root root     21 Mar 12 18:06 /usr/lib/libgvm_util.so.11 -> libgvm_util.so.11.0.0
-rw-r--r-- 1 root root 284168 Mar 12 18:06 /usr/lib/libgvm_util.so.11.0.0
```

### Environment

**Operating system:**
```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

# uname -a
Linux root360-backend-prod-gvm 5.3.0-40-generic #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Installation method / source:** (packages, source installation)
Build from sources based on [GVM-11](https://community.greenbone.net/t/gvm-11-stable-initial-release-2019-10-14/3674) using:
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DLOCALSTATEDIR=/var -DSYSCONFDIR=/etc .`

### Logfiles

I could not find any logs explaining the behaviour.
For completeness of this report, here are the last 10 lines of all gvm-logfiles:
```
# tail /var/log/gvm/*
==> /var/log/gvm/gsad.log <==
gsad main:MESSAGE:2020-03-16 08h23.04 utc:22711: Starting GSAD version 9.0

==> /var/log/gvm/gvmd.log <==
md   main:MESSAGE:2020-03-15 14h58.24 utc:16948:    Greenbone Vulnerability Manager version 9.0.0 (DB revision 221)
md manage:WARNING:2020-03-15 14h58.24 utc:16948: database must be initialised from scanner
util gpgme:MESSAGE:2020-03-15 14h58.24 utc:16948: Setting GnuPG dir to '/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-03-15 14h58.24 utc:16948: Using OpenPGP engine version '2.2.4'
md   main:MESSAGE:2020-03-16 08h23.04 utc:22709:    Greenbone Vulnerability Manager version 9.0.0 (DB revision 221)
md manage:WARNING:2020-03-16 08h23.05 utc:22709: database must be initialised from scanner
util gpgme:MESSAGE:2020-03-16 08h23.05 utc:22709: Setting GnuPG dir to '/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-03-16 08h23.05 utc:22709: Using OpenPGP engine version '2.2.4'
md manage:WARNING:2020-03-16 08h23.11 utc:22741: manage_update_nvt_cache_osp: failed to connect to /var/run/ospd/ospd.sock
md manage:WARNING:2020-03-16 08h23.21 utc:22749: manage_update_nvt_cache_osp: failed to connect to /var/run/ospd/ospd.sock

==> /var/log/gvm/openvas.log <==
sd   main:MESSAGE:2020-03-12 16h51.42 utc:25298: The remote host ::1 is dead
lib  nasl:MESSAGE:2020-03-12 16h51.42 utc:25314: [25314](/var/lib/openvas/plugins/nmap.nasl:142) script_get_preference_file_content: could not get  size of file from preference File containing grepable results : 
sd   main:MESSAGE:2020-03-12 16h51.42 utc:25298: Finished testing ::1. Time : 0.08 secs
lib  nasl:MESSAGE:2020-03-12 16h51.46 utc:25371: [25371](/var/lib/openvas/plugins/gb_default_credentials_options.nasl:92) script_get_preference_file_content: could not get  size of file from preference Credentials file:
lib  nasl:MESSAGE:2020-03-12 16h52.28 utc:25962: Function ssh_login called from ssh_proto_version.nasl: Failed to set SSH key type 'rsa-sha2-512': Setting method: no algorithm for method "server host key algo" (rsa-sha2-512)
lib  nasl:MESSAGE:2020-03-12 16h52.28 utc:25962: Function ssh_login called from ssh_proto_version.nasl: Failed to set SSH key type 'rsa-sha2-256': Setting method: no algorithm for method "server host key algo" (rsa-sha2-256)
lib  nasl:MESSAGE:2020-03-12 17h12.30 utc:30281: [30281](/var/lib/openvas/plugins/Policy/gb_policy_cpe.nasl:65) script_get_preference_file_content: could not get  size of file from preference CPE List
sd   main:MESSAGE:2020-03-12 17h12.35 utc:25299: Finished testing 127.0.0.1. Time : 1252.43 secs
sd   main:MESSAGE:2020-03-12 17h12.35 utc:25261: Test complete
sd   main:MESSAGE:2020-03-12 17h12.35 utc:25261: Total time to scan all hosts : 1256 seconds

==> /var/log/gvm/ospd-scanner.log <==
2020-03-12 15:41:51,668 OSPD - openvas: ERROR: (ospd_openvas.daemon) OpenVAS Scanner failed to load NVTs. Command '['openvas', '--update-vt-info']' died with <Signals.SIGABRT: 6>.
2020-03-12 15:48:03,550 OSPD - openvas: ERROR: (ospd_openvas.daemon) OpenVAS Scanner failed to load NVTs. Command '['openvas', '--update-vt-info']' died with <Signals.SIGABRT: 6>.
2020-03-12 16:08:49,960 OSPD - openvas: ERROR: (ospd_openvas.daemon) OpenVAS Scanner failed to load NVTs. Command '['openvas', '--update-vt-info']' died with <Signals.SIGABRT: 6>.
```

I hope you can reproduce this issue with these information.

Regards,
Andreas

**Comment by root360-AndreasUlm** [comment]
I checked the latest version of branch gsa-9.0 and this issue still exists.

**Comment by greatquux** [comment]
Affecting me as well, the results shows the override symbol, but is not being filtered out in the report view or when exporting the report.

![image](https://user-images.githubusercontent.com/1655942/82453358-6ccaac80-9a7e-11ea-8750-1bcfd4f7a633.png)

**Comment by Virsacer** [comment]
Same here...
I just noticed this thread but I did post my issue in the community: https://community.greenbone.net/t/overrides-not-applied/5129

**Comment by Virsacer** [comment]
This seems to be fixed in 11.0.1
However reports migrated from 11.0.0 (and before) are still affected - only new reports are working as expected...

**Comment by ozgursuder** [comment]
This problem persists in version 11.0.1

**Comment by timopollmeier** [comment]
If only old results do not have the overrides applied correctly, maybe `gvmd --optimize cleanup-result-nvts` could help.
If the result counts of old reports are wrong after this, you can try running `gvmd --optimize rebuild-report-cache`.
Keep in mind that these can take some time to run depending on the number of results in the database.

If this doesn't help, maybe some conditions of the overrides are not applied correctly. In this case, can you tell me which ones are set to "any" and which one are set to another value?

**Comment by root360-AndreasUlm** [comment]
Thanks for the commands I ran those with the following output:
```
root@gvm:~# sudo -u gvm -H gvmd --optimize cleanup-result-nvts
Optimized: Cleaned up result_nvts.
root@gvm:~# sudo -u gvm -H gvmd --optimize rebuild-report-cache
Optimized: rebuild-report-cache. Result counts recalculated for 644 reports.
```

The result in the webinterface is still the same:
![image](https://user-images.githubusercontent.com/17042256/92363205-73466800-f0f1-11ea-87f2-24d505b6ade8.png)

The override is defined as follows:
![image](https://user-images.githubusercontent.com/17042256/92363404-bb658a80-f0f1-11ea-8816-78dd6406e377.png)
(task is choosen to be the one in the screenshot above)

According to the symbol in the report list, the override applies:
![image](https://user-images.githubusercontent.com/17042256/92363583-febff900-f0f1-11ea-8889-46cd1722b7a0.png)
