### ISSUE TITLE
9.0.0 not compiling - babel-loader version mismatch in react

### ISSUE THREAD

**Issue by antgel** [greenbone/gsa#2124]
I'm trying to build 9.0.0 from git. I get the following - is this expected? Should I skip the preflight check?

Edit: I got the build to continue with `cd ../gsa && npm install babel-loader@8.1.0`, but not sure if that could break things.

```
antony@openvas-us-east1:~/src/git/gsa/build$ make -j2
-- Found Git: /usr/bin/git (found version "2.20.1") 
[  0%] Built target revisiontag                                        
[  5%] Build gsa-ng install files                                                 
[ 94%] Built target gsad                                                     
                                     
> gsa@9.0.0 build /home/antony/src/git/gsa/gsa    
> react-scripts build                             
                                                 
                                             
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.
                                                                  
The react-scripts package provided by Create React App requires a dependency:
                                                              
  "babel-loader": "8.1.0"             
                      
Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /home/antony/src/git/gsa/gsa/node_modules/babel-loader (version: 8.0.5)
```

I could go on but I think that should be enough...

**Comment by bjoernricks** [comment]
Did you try the release branch gsa-9.0?

**Comment by antgel** [comment]
@bjoernricks Thanks for the response, great catch. I had checked out tag v9.0.0, but now I see the branches are more up to date, so have rebuilt gvm-libs, openvas, and gsa, and the issue is indeed fixed. I have another issue now with gsad `Oops, secure memory pool already initialized`, but I'll open another issue for that. Thanks again.

**Comment by bjoernricks** [comment]
> Oops, secure memory pool already initialized

No need to create a new issue. It is already known and only a warning. Can be ignored.

**Comment by antgel** [comment]
> > Oops, secure memory pool already initialized
> 
> No need to create a new issue. It is already known and only a warning. Can be ignored.

Hmm. Well, my gsad isn't starting up, just coming back to the command line even with `-f`. I'll see what I can dig up.
