### ISSUE TITLE
Unable to create task

### ISSUE THREAD

**Issue by ChromeSilver** [greenbone/gsa#2211]
Hi Everyone,

after creating a target like 192.168.x.0/24 I tried to configure a new task for scanning this target but always get the error "Bogus element: usage_type". After some research this could be related to incompatible gvm version, but I did not find any clue how to alter that. 

### Expected behavior
Successfully creating a task.

### Actual behavior
Error Message: Bogus element: usage_type and dialogue box does not close.

### Steps to reproduce
1. Log in to GSA
2. Create Target via Configuration --> Targets --> New Target
3. Create Task via Scans --> Taks --> New Task
4. Select previously created Target as Scan Target
5. Click Save button
6. Error messageshows and dialogue does not close.No Task is created

### GVM versions

**gsa:** gsad --version
Greenbone Security Assistant 9.0.1

**gvm:** gvmd --version
Greenbone Vulnerability Manager 8.0.1

**gvm-libs:** pacman -Ss gvm-libs
community/gvm-libs 10.0.1-2 (greenbone-vulnerability-manager) [Installiert]
    greenbone-vulnerability-manager libraries

### Environment

**Operating system:** uname -a
Linux asgard 5.6.15-arch1-1 #1 SMP PREEMPT Wed, 27 May 2020 23:42:26 +0000 x86_64 GNU/Linux

**Installation method / source:** https://wiki.archlinux.org/index.php/OpenVAS

### Logfiles

cat gsad.log 
...
gsad main:MESSAGE:2020-06-04 10h02.39 utc:129652: Starting GSAD version 9.0.1
gsad  gmp:MESSAGE:2020-06-04 10h02.50 utc:129652: Authentication success for 'admin' from 127.0.0.1
gsad  gmp:MESSAGE:2020-06-04 10h25.30 UTC:129652: Authentication success for 'admin' from 127.0.0.1
...

cat gvmd.log
...
event task:MESSAGE:2020-06-04 10h33.08 UTC:167526: Status of task  (9e54b2d4-3c7f-4bb4-8200-71dd0f47673f) has changed to New
md    gmp:   INFO:2020-06-04 10h33.08 UTC:167526:    Failed to parse client XML: Error
...

**Comment by bjoernricks** [comment]
>gvm: gvmd --version
Greenbone Vulnerability Manager 8.0.1

You are using a wrong gvmd version. It needs to be version 9.0.1. You can't mix components from different GVM releases.
