### ISSUE TITLE
Rethink responses for plural commands

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#23]
Currently all plural commands (commands to return lists like gmp.tasks.get()) return CollectionLists
directly. The collection list had the intention to provide the list counts at first and got extended to also provide meta information about the http response. Afterwards getting meta info got also necessary for single commands (for a specific entity like gmp.taks.get({id})). As a result single commands return a Response class instead of the entity model directly.

To have a more consistent API it may be better to also return Response objects for plural commands. The API would change from
```javascript
gmp.tasks.get().then(collectionlist => {
  const data = collectionslist;
  const {meta, counts} = data;
});
```
to

```javascript
gmp.tasks.get().then(response => {
  const {meta, data: collectionlist} = response;
  const {counts} = collectionlist;
});
```

which is more aligned to the single command API

```javascript
gmp.task.get({id: 1}).then(response => {
  const {meta, data: task} = response;
});
```

**Comment by bjoernricks** [comment]
I have also thought about putting the counts into the response too
```javascript
gmp.tasks.get().then(response => {
  const {meta, data: collectionlist, counts} = response;
});
```
In this case collectionslist can be an instance of Array instead of our own CollectionList class. But that would also mean to write a second response class because the response object for single entity commands should not have a counts property.

**Comment by bjoernricks** [comment]
Hmm it would be easy to put the counts into the meta
```javascript
gmp.tasks.get().then(response => {
  const {meta, data: collectionlist} = response;
  const {counts} = meta;
});
```
But I am not really sure if it is correct semantically. Are counts part of the response meta information ...?

**Comment by swaterkamp** [comment]
We should omit a second response class for brevity's sake just because of the counts. That is a little too much and problably produces a lot of duplicate code.

Putting the counts into the meta information, on the other hand, is semantically absolutely senseful, and reduces code changes to a minimum.

**Comment by bjoernricks** [comment]
Thanks. So we'll go for:
```javascript
gmp.tasks.get().then(response => {
  const {meta, data: collectionlist} = response;
  const {counts} = meta;
});
```
collectionlist will be an Array and the CollectionList class will be obsolete then.
