### ISSUE TITLE
Review unused functions

### ISSUE THREAD

**Issue by wiegandm** [greenbone/gsa#230]
Code analysis with `cppcheck` shows four functions in GSA which are
defined, but never used:

- gsad/src/gsad_cmd.c: cmd_response_data_set_redirect ()
- gsad/src/xslt_i18n.c: get_ext_gettext_enabled ()
- gsad/src/gsad_http_handler.c: handle_login_page ()
- gsad/src/gsad_http.c: is_export ()

It should check whether this is indeed dead code or code waiting to be
used.

**Comment by bjoernricks** [comment]
gsad/src/gsad_http_handler.c: handle_login_page () can be removed. It's unused since the xslt code got removed and the login is always done via ng.

**Comment by timopollmeier** [comment]
I think pretty much all of xslt_i18n.c is only for the XSLT extensions we used for translations.
So we should make sure ng works independently with only the user settings and eventually remove the file.

For gsad/src/gsad_cmd.c:cmd_response_data_set_redirect() and gsad/src/gsad_http.c:is_export() I can't tell at a glance if it makes sense to use them in the new HTTP handler (maybe after some refactoring) of it they are really obsolete.

**Comment by bjoernricks** [comment]
the next param can also be removed. It's obsolete with ng.
