### ISSUE TITLE
Portlists cannot be updated via GSA

### ISSUE THREAD

**Issue by wisukind** [greenbone/gsa#2305]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**Current behaviour:**
Currently it's not possible to import updated IANA's portlist from the Configuration >> Port Lists menu. Importing an XML file from IANA will generate the following error:
`md    gmp:   INFO:2020-07-10 14h58.10 UTC:2280:    Failed to parse client XML: Error on line 15900 char 28: '<' is not a valid name`

It seems the only way to import an updated port list is using the internal gvm-portnames-update tool, but it's unclear what effect is has with existing port lists being used by tasks. In gsad, port lists are still seen as being last updated in 2012 !

**Expected behaviour:**
It should be possible to update port lists via GSAD Port Lists configuration menu, using XML port lists provided by IANA.

**Comment by bjoernricks** [comment]
Hi,

it isn't possible to import IANA XML port lists in GSA. This import is for importing previously exported port lists from GSA.

Therefore I am closing this issue for now. Please feel free to reopen if I did get something wrong.
