### ISSUE TITLE
Stop button doesn't hanle tasks stuck in Requested status

### ISSUE THREAD

**Issue by wisukind** [greenbone/gsa#2306]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```
**Current behaviour:**
If for whatever reason a task is stuck in Requested status, which happens occasionally, task cannot be reset; preventing any other action on this task (stop button is greyed out and therefore unavailable). The only way to reset this task is to actually restart gvmd.

**Expected behaviour:**
When a task is in Requested status; the stop button shouldn't be greyed out and should be available to cancel that task anyway.

**Comment by y0urself** [comment]
If this is relevant for 20.08 or 21.04, please recreate/reopen.
