### ISSUE TITLE
Insecure feature: Download Windows Executable

### ISSUE THREAD

**Issue by bananabr** [greenbone/gsa#2360]
Please refer to https://github.com/greenbone/openvas/issues/563. I didn't want to replicate it but this is probably the right repo to report it.

**Comment by bjoernricks** [comment]
We are already looking into it and working on the issue

**Comment by cfi-gb** [comment]
@bjoernricks @bananabr I have transferred https://github.com/greenbone/gvmd/issues/1228 to the correct repository (GVMD is responsible for the generation of the credential installer) and i guess this issue could be closed as a duplicate (or even deleted).

**Comment by bjoernricks** [comment]
@cfi-gb i'll close it as duplicate of https://github.com/greenbone/gvmd/issues/1228
