### ISSUE TITLE
[20.8.0] No old reports are shown after update from gsa(9), gvmd(9)

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#2433]
### Expected behavior

That I see the old reports

### Actual behavior

On GSA only this message is shown:
![Screenshot_2020-09-01 Greenbone Security Assistant](https://user-images.githubusercontent.com/837503/91842386-3e9b6200-ec54-11ea-9a53-c3bd43e9c064.png)

In the log file of gvm this error is logged:
md manage:WARNING:2020-09-01 13h00.44 CEST:31159: run_report_format_script: No generate script found at /var/lib/greenbone/gvmd/report_formats/generate

### Steps to reproduce
1. Update gvmd
2. Update gsa
3. migrate the postgres db
4. Try to show the old reports

### GVM versions

**gsa:** Greenbone Security Assistant 20.08.0~git

**gvm:**
Greenbone Vulnerability Manager 20.08.0
Manager DB revision 233

**openvas-scanner:** 
OpenVAS 20.8.0
gvm-libs 20.8.0

**gvm-libs:** gvm-libs 20.8.0

### Environment

**Operating system:** CentOS 7.8

**Installation method / source:** Source files from git

**Comment by tuxmaster5000** [comment]
Here the log of the migration process:
```
md   main:MESSAGE:2020-09-01 11h31.00 utc:5510:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating database.
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 222
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 223
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 224
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 225
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 226
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 227
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 228
md   main:   INFO:2020-09-01 11h31.00 utc:5510: migrate_227_to_228: deleted 297 results of dead report hosts
md   main:   INFO:2020-09-01 11h31.00 utc:5510: migrate_227_to_228: deleted 262 trashcan results of dead report hosts
md   main:   INFO:2020-09-01 11h31.00 utc:5510: migrate_227_to_228: deleted 20 dead report hosts
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 229
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 230
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 231
md   main:   INFO:2020-09-01 11h31.00 utc:5510:    Migrating to 232
md   main:   INFO:2020-09-01 11h31.01 utc:5510:    Migrating to 233
md   main:   INFO:2020-09-01 11h31.01 utc:5510:    Analyzing the database. This may take up to several hours.
md   main:   INFO:2020-09-01 11h31.15 utc:5510:    Migration succeeded.
```

**Comment by mattmundell** [comment]
This is because the Feed Import Owner needs to be set.

https://github.com/greenbone/gsa/pull/2367 improves the GSA error message.

**Comment by mattmundell** [comment]
> This is because the Feed Import Owner needs to be set.

See the https://github.com/greenbone/gvmd/blob/master/INSTALL.md#set-the-feed-import-owner for how to do this.

Closing, because it's expected behaviour.
