### ISSUE TITLE
[20.08] Unable to start gsad because of missing certificates

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gsa#2455]
### Expected behavior
gsad start without problems.

### Actual behavior
gsad wont start with because of the folowing error:
```
gsad main:MESSAGE:2020-09-15 08h52.09 utc:5097: Starting GSAD version 20.08.0~git-d26e061f9-gsa-20.08
gsad main:CRITICAL:2020-09-15 08h52.09 utc:5098: main: Could not load private SSL key from /opt/gvm/var/lib/gvm/private/CA/serverkey.pem: Failed to open file “/opt/gvm/var/lib/gvm/private/CA/serverkey.pem”: No such file or directory
```
Even when I specify a custom SSL certificate and key, the error keeps coming.

### Steps to reproduce
Build gsad from git commit d26e061f9

### GVM versions
20.08.0~git-d26e061f9-gsa-20.08

### Environment
CentOs

**Comment by BasvanH** [comment]
I've done a fresh install which deleted my certificates. Just run a `gvm-manage-certs -a` and the certs are generated again.

**Comment by rajeshrd13** [comment]
sudo chmod 644 /var/lib/gvm/private/CA/*     helped me.
