### ISSUE TITLE
/opt/gvm/src/gsa/gsad/src/gsad_gmp.c:16654:12: error: ‘gmp_authenticate_info_opts_t’ {aka ‘struct <anonymous>’} has no member named ‘severity’

### ISSUE THREAD

**Issue by jstevensog** [greenbone/gsa#2470]
### Expected behavior

gsad builds successfully from source pulled from git.

### Actual behavior

/opt/gvm/src/gsa/gsad/src/gsad_gmp.c: In function ‘authenticate_gmp’:
/opt/gvm/src/gsa/gsad/src/gsad_gmp.c:16654:12: error: ‘gmp_authenticate_info_opts_t’ {aka ‘struct <anonymous>’} has no member named ‘severity’
   auth_opts.severity = severity;
            ^
make[2]: *** [gsad/src/CMakeFiles/gsad.dir/build.make:115: gsad/src/CMakeFiles/gsad.dir/gsad_gmp.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: gsad/src/CMakeFiles/gsad.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

### Steps to reproduce

from established local git repos for all GSE components,
1.  Pull latest 
2.  Configure (if required)
3.  make clean && make

### GVM versions
gsad version cannot build.
Greenbone Vulnerability Manager 21.4.0~dev1~git-02dbb172-master
OpenVAS 21.4.0~dev1~git-c84f5bd9-master
gvm-libs 21.4.0~dev1~git-ae7e1274-master

### Environment
CentOS 8
4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Built from source.

**Comment by bjoernricks** [comment]
Fixed with https://github.com/greenbone/gsa/pull/2471
