### ISSUE TITLE
Fail to create a task with "Failed to find port_list '33d0cd82-57c6-11e1-8ed1-406186ea4fc5'"

### ISSUE THREAD

**Issue by montjoie** [greenbone/gsa#2497]
### Expected behavior

I should be able to create a task

### Actual behavior

Create a task via "task wizard" fail with "Failed to find port_list '33d0cd82-57c6-11e1-8ed1-406186ea4fc5'"

### Steps to reproduce

Produce a fresh new install, run, test

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 20.08.0~git

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 20.08.0
Manager DB revision 233

OpenVAS 20.8.0
gvm-libs 20.8.0

### Environment

Debian buster

Install from sources

### Logfiles

md   main:MESSAGE:2020-10-09 05h29.00 utc:170:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md manage:   INFO:2020-10-09 05h29.00 utc:170:    Creating user.
md manage:WARNING:2020-10-09 05h29.00 utc:170: sql_exec_internal: PQexec failed: ERROR:  relation "public.meta" does not exist
LINE 1: SELECT value FROM public.meta WHERE name = 'database_version...
                          ^
 (7)
md manage:WARNING:2020-10-09 05h29.00 utc:170: sql_exec_internal: SQL: SELECT value FROM public.meta WHERE name = 'database_version';
md manage:WARNING:2020-10-09 05h29.00 utc:170: sql_x: sql_exec_internal failed
md manage:MESSAGE:2020-10-09 05h29.00 utc:170: No SCAP database found
md manage:MESSAGE:2020-10-09 05h29.00 utc:170: No CERT database found
md   main:MESSAGE:2020-10-09 05h29.11 utc:174:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md manage:MESSAGE:2020-10-09 05h29.13 utc:175: No SCAP database found
md manage:MESSAGE:2020-10-09 05h29.13 utc:175: No CERT database found
util gpgme:MESSAGE:2020-10-09 05h29.13 utc:175: Setting GnuPG dir to '/usr/local/var/lib/gvm/gvmd/gnupg'
util gpgme:MESSAGE:2020-10-09 05h29.13 utc:175: Using OpenPGP engine version '2.2.12'
md manage:   INFO:2020-10-09 05h29.13 utc:207: Initializing CERT database
md manage:WARNING:2020-10-09 05h29.13 utc:205: update_scap: No SCAP db present, rebuilding SCAP db from scratch
md manage:   INFO:2020-10-09 05h29.15 utc:207: sync_cert: Updating data from feed
md manage:   INFO:2020-10-09 05h29.15 utc:207: update_dfn_xml: dfn-cert-2018.xml
md manage:   INFO:2020-10-09 05h29.15 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2018.xml
md manage:   INFO:2020-10-09 05h29.16 utc:205: update_scap: Updating data from feed
md manage:   INFO:2020-10-09 05h29.16 utc:205: Updating CPEs
md manage:   INFO:2020-10-09 05h29.19 utc:207: update_dfn_xml: dfn-cert-2020.xml
md manage:   INFO:2020-10-09 05h29.19 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2020.xml
md manage:   INFO:2020-10-09 05h29.22 utc:207: update_dfn_xml: dfn-cert-2011.xml
md manage:   INFO:2020-10-09 05h29.22 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2011.xml
md manage:   INFO:2020-10-09 05h29.24 utc:207: update_dfn_xml: dfn-cert-2017.xml
md manage:   INFO:2020-10-09 05h29.24 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2017.xml
md manage:   INFO:2020-10-09 05h29.26 utc:207: update_dfn_xml: dfn-cert-2016.xml
md manage:   INFO:2020-10-09 05h29.26 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2016.xml
md manage:   INFO:2020-10-09 05h29.29 utc:207: update_dfn_xml: dfn-cert-2019.xml
md manage:   INFO:2020-10-09 05h29.29 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2019.xml
md manage:   INFO:2020-10-09 05h29.33 utc:207: update_dfn_xml: dfn-cert-2008.xml
md manage:   INFO:2020-10-09 05h29.33 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2008.xml
md manage:   INFO:2020-10-09 05h29.33 utc:207: update_dfn_xml: dfn-cert-2015.xml
md manage:   INFO:2020-10-09 05h29.33 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2015.xml
md manage:   INFO:2020-10-09 05h29.35 utc:207: update_dfn_xml: dfn-cert-2012.xml
md manage:   INFO:2020-10-09 05h29.35 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2012.xml
md manage:   INFO:2020-10-09 05h29.36 utc:207: update_dfn_xml: dfn-cert-2013.xml
md manage:   INFO:2020-10-09 05h29.36 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2013.xml
md manage:   INFO:2020-10-09 05h29.38 utc:207: update_dfn_xml: dfn-cert-2009.xml
md manage:   INFO:2020-10-09 05h29.38 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2009.xml
md manage:   INFO:2020-10-09 05h29.39 utc:207: update_dfn_xml: dfn-cert-2010.xml
md manage:   INFO:2020-10-09 05h29.39 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2010.xml
md manage:   INFO:2020-10-09 05h29.40 utc:207: update_dfn_xml: dfn-cert-2014.xml
md manage:   INFO:2020-10-09 05h29.40 utc:207: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2014.xml
md manage:   INFO:2020-10-09 05h29.42 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K18.xml
md manage:   INFO:2020-10-09 05h29.43 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K14.xml
md manage:   INFO:2020-10-09 05h29.45 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K13.xml
md manage:   INFO:2020-10-09 05h29.46 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K16.xml
md manage:   INFO:2020-10-09 05h29.48 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K15.xml
md manage:   INFO:2020-10-09 05h29.50 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K20.xml
md manage:   INFO:2020-10-09 05h29.51 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K17.xml
md manage:   INFO:2020-10-09 05h29.54 utc:207: Updating /usr/local/var/lib/gvm/cert-data/CB-K19.xml
md manage:   INFO:2020-10-09 05h29.56 utc:207: Updating Max CVSS for DFN-CERT
md manage:WARNING:2020-10-09 05h29.56 utc:207: sql_exec_internal: PQexec failed: ERROR:  relation "scap.cves" does not exist
LINE 1: ...ax_cvss = (SELECT max (cvss)                 FROM scap.cves ...
                                                             ^
 (7)
md manage:WARNING:2020-10-09 05h29.56 utc:207: sql_exec_internal: SQL: UPDATE cert.dfn_cert_advs SET max_cvss = (SELECT max (cvss)                 FROM scap.cves                 WHERE name                 IN (SELECT cve_name                     FROM cert.dfn_cert_cves                     WHERE adv_id = dfn_cert_advs.id)                 AND cvss != 0.0);
md manage:WARNING:2020-10-09 05h29.56 utc:207: sqlv: sql_exec_internal failed
md manage:   INFO:2020-10-09 05h31.06 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2008.xml
md manage:   INFO:2020-10-09 05h31.33 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2015.xml
md manage:   INFO:2020-10-09 05h31.58 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2016.xml
md manage:   INFO:2020-10-09 05h32.23 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2007.xml
event asset:MESSAGE:2020-10-09 05h32.28 UTC:766: Asset 90d06f31-114d-43c8-bc70-b290ac9a6eb9 has been created by admin
md manage:   INFO:2020-10-09 05h32.40 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2004.xml
md manage:   INFO:2020-10-09 05h32.48 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2014.xml
event target:MESSAGE:2020-10-09 05h33.10 UTC:909: Target could not be created by admin
md manage:   INFO:2020-10-09 05h33.23 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2017.xml
event port_list:MESSAGE:2020-10-09 05h33.31 UTC:936: Port List Portlist de base (87a67fdc-d2a3-4451-91c0-c0f5fba2ec61) has been created by admin
event target:MESSAGE:2020-10-09 05h33.34 UTC:948: Target Unnamed (bcfc99fc-823b-40df-a2e5-9e0578f847e0) has been created by admin
event task:MESSAGE:2020-10-09 05h33.52 UTC:976: Status of task  (af1de23f-019f-45e3-97f6-b923f26dcdb9) has changed to New
event task:MESSAGE:2020-10-09 05h34.24 UTC:1031: Status of task  (2e4d5a0c-093c-48c7-8b5e-0dfac9a648a3) has changed to New
md manage:   INFO:2020-10-09 05h34.35 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2013.xml
event task:MESSAGE:2020-10-09 05h34.44 UTC:1054: Status of task  (15bd5cce-805c-417b-b775-6bca78d06188) has changed to New
md manage:   INFO:2020-10-09 05h35.08 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2003.xml
md manage:   INFO:2020-10-09 05h35.18 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2018.xml
event target:MESSAGE:2020-10-09 05h36.01 UTC:1180: Target could not be created by admin
event wizard:MESSAGE:2020-10-09 05h36.01 UTC:1180: Wizard quick_task could not be run by admin
md manage:   INFO:2020-10-09 05h37.02 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2020.xml
md manage:   INFO:2020-10-09 05h38.07 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2012.xml
md   main:MESSAGE:2020-10-09 05h38.47 utc:1265:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md   main:WARNING:2020-10-09 05h38.47 utc:1265: gvmd: Main process is running, refusing to migrate
md manage:   INFO:2020-10-09 05h39.08 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2002.xml
md manage:   INFO:2020-10-09 05h39.37 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2010.xml
md manage:   INFO:2020-10-09 05h40.17 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2009.xml
md manage:   INFO:2020-10-09 05h41.05 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2011.xml
md manage:   INFO:2020-10-09 05h41.44 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2006.xml
md manage:   INFO:2020-10-09 05h42.22 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2005.xml
md manage:   INFO:2020-10-09 05h42.43 utc:205: Updating /usr/local/var/lib/gvm/scap-data/nvdcve-2.0-2019.xml
md manage:   INFO:2020-10-09 05h46.12 utc:205: Updating OVAL data
md manage:   INFO:2020-10-09 05h46.21 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/c/oval.xml
md manage:   INFO:2020-10-09 05h46.21 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/m/oval.xml
md manage:   INFO:2020-10-09 05h46.21 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/v/family/ios.xml
md manage:   INFO:2020-10-09 05h46.25 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/v/family/pixos.xml
md manage:   INFO:2020-10-09 05h46.25 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/p/oval.xml
md manage:   INFO:2020-10-09 05h47.51 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/i/oval.xml
md manage:   INFO:2020-10-09 05h47.53 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/v/family/macos.xml
md manage:   INFO:2020-10-09 05h47.53 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/v/family/unix.xml
md manage:   INFO:2020-10-09 05h47.58 utc:205: Updating /usr/local/var/lib/gvm/scap-data/oval/5.10/org.mitre.oval/v/family/windows.xml
md manage:   INFO:2020-10-09 05h48.04 utc:205: Updating user OVAL definitions.
md manage:   INFO:2020-10-09 05h48.04 utc:205: Updating CVSS scores and CVE counts for CPEs
md manage:   INFO:2020-10-09 06h02.59 utc:205: Updating CVSS scores for OVAL definitions
md manage:   INFO:2020-10-09 06h03.34 utc:205: Updating placeholder CPEs
md manage:   INFO:2020-10-09 06h10.07 utc:205: Updating Max CVSS for DFN-CERT
md manage:   INFO:2020-10-09 06h11.08 utc:205: Updating DFN-CERT CVSS max succeeded.
md manage:   INFO:2020-10-09 06h11.08 utc:205: Updating Max CVSS for CERT-Bund
md manage:   INFO:2020-10-09 06h11.17 utc:205: Updating CERT-Bund CVSS max succeeded.
md manage:   INFO:2020-10-09 06h11.25 utc:205: update_scap_end: Updating SCAP info succeeded
md manage:   INFO:2020-10-09 06h11.41 utc:1536: sync_cert: Updating data from feed
md manage:   INFO:2020-10-09 06h11.41 utc:1536: update_dfn_xml: dfn-cert-2018.xml
md manage:   INFO:2020-10-09 06h11.41 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2018.xml
md manage:   INFO:2020-10-09 06h11.42 utc:1536: update_dfn_xml: dfn-cert-2020.xml
md manage:   INFO:2020-10-09 06h11.42 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2020.xml
md manage:   INFO:2020-10-09 06h11.42 utc:1536: update_dfn_xml: dfn-cert-2011.xml
md manage:   INFO:2020-10-09 06h11.42 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2011.xml
md manage:   INFO:2020-10-09 06h11.44 utc:1536: update_dfn_xml: dfn-cert-2017.xml
md manage:   INFO:2020-10-09 06h11.44 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2017.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2016.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2016.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2019.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2019.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2008.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2008.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2015.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2015.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2012.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2012.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: update_dfn_xml: dfn-cert-2013.xml
md manage:   INFO:2020-10-09 06h11.45 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2013.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: update_dfn_xml: dfn-cert-2009.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2009.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: update_dfn_xml: dfn-cert-2010.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2010.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: update_dfn_xml: dfn-cert-2014.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/dfn-cert-2014.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K18.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K14.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K13.xml
md manage:   INFO:2020-10-09 06h11.46 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K16.xml
md manage:   INFO:2020-10-09 06h11.47 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K15.xml
md manage:   INFO:2020-10-09 06h11.47 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K20.xml
md manage:   INFO:2020-10-09 06h11.47 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K17.xml
md manage:   INFO:2020-10-09 06h11.47 utc:1536: Updating /usr/local/var/lib/gvm/cert-data/CB-K19.xml
md manage:   INFO:2020-10-09 06h11.48 utc:1536: Updating Max CVSS for DFN-CERT
md manage:   INFO:2020-10-09 06h11.52 utc:1536: Updating DFN-CERT CVSS max succeeded.
md manage:   INFO:2020-10-09 06h11.52 utc:1536: Updating Max CVSS for CERT-Bund
md manage:   INFO:2020-10-09 06h11.53 utc:1536: Updating CERT-Bund CVSS max succeeded.
md manage:   INFO:2020-10-09 06h11.53 utc:1536: sync_cert: Updating CERT info succeeded.
md   main:MESSAGE:2020-10-09 06h24.01 utc:2043:    Greenbone Vulnerability Manager version 20.08.0 (DB revision 233)
md manage:   INFO:2020-10-09 06h24.01 utc:2043:    Getting scanners.
event target:MESSAGE:2020-10-09 06h26.00 UTC:2274: Target could not be created by admin
event wizard:MESSAGE:2020-10-09 06h26.00 UTC:2274: Wizard quick_task could not be run by admin
event task:MESSAGE:2020-10-09 06h26.57 UTC:2498: Status of task  (a7580bd9-f558-47ba-b92f-9c8381cb656d) has changed to New
event task:MESSAGE:2020-10-09 06h27.02 UTC:2504: Status of task  (3a3c8c70-a616-42f0-95af-fc04e3f8f1d9) has changed to New
event target:MESSAGE:2020-10-09 06h29.39 UTC:2681: Target could not be created by admin
event wizard:MESSAGE:2020-10-09 06h29.39 UTC:2681: Wizard quick_first_scan could not be run by admin

**Comment by cfi-gb** [comment]
@greenbone/gsa-dev I guess this should be moved into the gvmd repository.

@montjoie 33d0cd82-57c6-11e1-8ed1-406186ea4fc5 is the "All IANA assigned TCP" which is shipped with the GVMD_DATA feed since 20.08. If you're getting this message it is very likely that the following is valid for you as well:

> You're probably have missed to set the Feed Import user:
>
> https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#set-the-feed-import-owner
>
> or haven't synced the GVM_DATA feed yet / before:
>
> https://github.com/greenbone/gvmd/blob/v20.8.0/INSTALL.md#keeping-the-feeds-up-to-date

https://github.com/greenbone/gvmd/issues/1315#issuecomment-704067316

**Comment by montjoie** [comment]
I fixed by creating necessary directory, and adding the scanner.

**Comment by cfi-gb** [comment]
Good to know that you have found the way to setup your environment correctly.

For further problems like this please try to use the https://community.greenbone.net/c/gse first.

Only if it is confirmed that the problem is a bug and not just a setup issue like this it is still possible to raise a bug report in one of the github issue trackers.

**Comment by montjoie** [comment]
I will send a PR for making documentation more clear. People like me which have some habit from old openvas need to have a big sign like "no default scanner". And port configs etc...will come only after some actions.

**Comment by cfi-gb** [comment]
Sounds great, thanks :+1: 

Related to my previous comment: I know it isn't always that easy to exactly know if something is really a bug or just a setup / configuration issue. :frowning_face: 

But posting at the community portal first helps to keep the communication channels clean (support questions at the community portal, "real" bugs at the github issue trackers). There the correct repository for a possible bug report could be named as well (e.g. default scanner and such things like port lists are handled by [gvmd](https://github.com/greenbone/gvmd) and not by gsa).

Thanks again

**Comment by frafios** [comment]
> I fixed by creating necessary directory, and adding the scanner.

I've same problem, please could you write step-by-step details?

tnx

**Comment by MarksenDE** [comment]
> > I fixed by creating necessary directory, and adding the scanner.
> 
> I've same problem, please could you write step-by-step details?
> 
> tnx

I fixed  it like this way:

create 3 subdirectories: 
- /var/lib/gvm/data-objects/gvmd/20.08/configs
- /var/lib/gvm/data-objects/gvmd/20.08/port_lists
- /var/lib/gvm/data-objects/gvmd/20.08/report_formats
- after creation i've started _greenbone-feed-sync --type GVMD_DATA_

HTH

**Comment by tsendsuren8** [comment]
> > > I fixed by creating necessary directory, and adding the scanner.
> > 
> > 
> > I've same problem, please could you write step-by-step details?
> > tnx
> 
> I fixed it like this way:
> 
> create 3 subdirectories:
> 
>     * /var/lib/gvm/data-objects/gvmd/20.08/configs
> 
>     * /var/lib/gvm/data-objects/gvmd/20.08/port_lists
> 
>     * /var/lib/gvm/data-objects/gvmd/20.08/report_formats
> 
>     * after creation i've started _greenbone-feed-sync --type GVMD_DATA_
> 
> 
> HTH

Its working fine. Thank you.

**Comment by JulioAviles** [comment]
Please help, same issue......
**asking before made a bad step !!**

https://community.greenbone.net/t/failed-to-find-port-list-33d0cd82-57c6-11e1-8ed1-406186ea4fc5/8771

**Comment by YWxtYXoK** [comment]
> Please help, same issue......
> **asking before made a bad step !!**
> 
> https://community.greenbone.net/t/failed-to-find-port-list-33d0cd82-57c6-11e1-8ed1-406186ea4fc5/8771

For me @MarksenDE's answer working fine. I'm thankful for the time saved

**Comment by rconiv** [comment]
Just to ask, since the instructions came out a year ago.  under gvmd, I have a 20.08, 21.10, and 21.04 folders.  Should I still put in the above new folders under 20.08, or one of the newer ones?  Help says I have 20.08, so going to do it there, but wanted to just ask for future reference.

**Comment by Squuiid** [comment]
This issue has returned with a clean Docker container build.

**Comment by cfi-gb** [comment]
@Squuiid Only FYI that the GSA is the "JavaScript" WebGUI part of the whole software stack and any missing port_list / what has been discussed here is completely unrelated to GSA.

Please follow this:

https://github.com/greenbone/gsa/issues/2497#issuecomment-706305394

and this:

https://github.com/greenbone/gsa/issues/2497#issuecomment-706328044

**Comment by bjoernricks** [comment]
Hi I am sorry the community container data-objects image is broken on our registry currently. We are working on a fix.

**Comment by bjoernricks** [comment]
This issue has been fixed a long time ago. The data-objects container image is fixed and should work. You don't need to run `greenbone-feed-sync` for the containers. Also if the data gets downloaded into a 22.04 directory by default you are not using the lastest version of `greenbone-feed-sync`

**Comment by Squuiid** [comment]
I genuinely don't believe this was ever resolved. I was told as much but have encountered the issue ever since, even after recreating everything from scratch. This issue absolutely persists despite what is being said by devs. I ended up giving up as there was no traction to fix this. @bjoernricks I do think you should try a new Ubuntu vm and go through the process of spinning up the Docker image from scratch. You will without a doubt encounter this issue.
