### ISSUE TITLE
Rename token to sessionToken

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#27]
The current gmp api uses the term token for the session token because the http "_protocol_" to gsad uses this variable. I fear the term token might be to generic in future and it may be better to use sessionToken instead.

The term token is used in gmp/gmp.js and gmp/http.js

**Comment by swaterkamp** [comment]
What do you expect to use "token" in the future? Right now it is quite specific, what token means, even though the term "token" is obviously generic.

**Comment by bjoernricks** [comment]
Not sure. I fear that we are getting another token (e.g. JWT https://en.wikipedia.org/wiki/JSON_Web_Token) and still need the current session token. IMHO sessionToken is a clearer name. But I am also not sure if it's worth the work.

**Comment by bjoernricks** [comment]
Thinking a bit more about it. When switching to something like JWT it wil replace the session token completely. Therefore we could still store the JWT token in the token variable. Also the JWT token would be a session token too.

I am closing this issue.
