### ISSUE TITLE
[20.8.1] Work only in http mode

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#2731]
Gsa will only start with the --http-only option.
When starting with an valid https configuration, then it fails with:
```
gsad main:MESSAGE:2021-02-16 08h40.09 utc:23354: Starting GSAD version 20.08.1~git
gsad main:  DEBUG:2021-02-16 08h40.09 utc:23354: Forking...
gsad main:  DEBUG:2021-02-16 08h40.09 utc:23355: Forking for redirect...
gsad main:CRITICAL:2021-02-16 08h40.09 utc:23355: main: start_https_daemon failed!
gsad http handler:  DEBUG:2021-02-16 08h40.09 utc:23355: Cleaning up http handlers
gsad main:  DEBUG:2021-02-16 08h40.09 utc:23356: GSAD started successfully and is redirecting on port 80.
gsad main:  DEBUG:2021-02-16 08h40.09 utc:23356: Received Terminated signal.
gsad http handler:  DEBUG:2021-02-16 08h40.09 utc:23356: Cleaning up http handlers
```
used:
Libmicrohttpd: 0.9.72
gnutls: 3.6.15
No error is shown why the https part fails.

**Comment by bjoernricks** [comment]
I've checked our code twice and nothing has changed in this regard. So this might very likely some setup issue.

**Comment by ciphermichael** [comment]
I am having similar issue. whenever i try to login 

root@scanner:/home/michael_lawrence# tail /opt/gvm/var/log/gvm/gsad.log -f
gsad main:WARNING:2021-02-18 00h01.24 utc:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.25 utc:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.32 utc:4373: MHD: Error: received handshake message out of context
gsad  gmp:MESSAGE:2021-02-18 00h01.32 utc:4373: Authentication success for 'admin' from 102.89.2.180
gsad main:WARNING:2021-02-18 00h01.33 UTC:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.33 UTC:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.35 UTC:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.35 UTC:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.35 UTC:4373: MHD: Error: received handshake message out of context
gsad main:WARNING:2021-02-18 00h01.35 UTC:4373: MHD: Error: received handshake message out of context


Keeps prompting for username and password

**Comment by ceylanb** [comment]
`gsad main:WARNING:2021-03-19 06h34.38 UTC:809: MHD: Error: received handshake message out of context.`

Same!

**Comment by bjoernricks** [comment]
As stated several time on other places

> gsad main:WARNING:2021-03-19 06h34.38 UTC:809: MHD: Error: received handshake message out of context.

Is not a bug. It is just a **warning** message. This can happen very often when the https client behaves incorrectly/unexpected.

**Comment by bjoernricks** [comment]
As I wrote before we didn't touch any code for https handling in the last releases. So please check your setup and the certificates in detail. Maybe it has also something to do with the linked gnutls library.
