### ISSUE TITLE
[21.04.0] Viewing of report in the ui fails, but download works.

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#2861]
### Expected behavior

That the scan  reports can be viewed in the ui 

### Actual behavior

Only the error:

> Error while loading Results for Report 291071ab-8467-4034-804d-fc3add8922c1
> Please try again.
is shown and under more this will be shown;

> TypeError: e is undefined
> 
> parseElement@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:57274
> fromElement@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:30710
> parseElement@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:83104
> fromElement@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:30710
> b/<@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:62218
> a@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:16089
> b@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:62170
> p@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:62641
> getCollectionListFromRoot@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:44189
> get/<@https://host.domain.net/static/js/main.b7014f22.chunk.js:1:44402

But when the report is exported as PDF for example, the file will contains the correct report.
The download of the XML and anonymous XML report also work. So I think it will be an problem of gsa and not the gvmd.

### Steps to reproduce

1. Let an scan run
2. open the report in the ui
3. viewing fails.
4.  Try to download the report -> will work

### GVM versions

**gsa:** Greenbone Security Assistant 21.04.0~git

**gvm:** Greenbone Vulnerability Manager 21.4.0
Manager DB revision 242

**openvas-scanner:** OpenVAS 21.4.0

**gvm-libs:** gvm-libs 21.4.0

### Environment

**Operating system:**

CentOS8 Stream

**Installation method / source:** From sources of github

**Comment by bjoernricks** [comment]
@tuxmaster5000 would it be possible to attach the (anonymized) XML export here?

**Comment by tuxmaster5000** [comment]
Here the anonymized report of the "self test" of gvmd

[report-291071ab-8467-4034-804d-fc3add8922c1.xml.gz](https://github.com/greenbone/gsa/files/6335642/report-291071ab-8467-4034-804d-fc3add8922c1.xml.gz)

**Comment by bjoernricks** [comment]
@tuxmaster5000 I am sorry I can't reproduce the issue on two different systems.

If you have some time to debug the issue you could try running the dev server (https://github.com/greenbone/gsa/blob/gsa-21.04/INSTALL.md#developing-greenbone-security-assistant-gui) to get a better non-minified traceback.

**Comment by tuxmaster5000** [comment]
It is very interesting, because the gvmd don't throw any errors, or warnings. But after an second "runuser -u gvmd -- gvmd --rebuild"
now the reports are shown in the ui.
Here are the anonymous report after the rebuild
[report-291071ab-8467-4034-804d-fc3add8922c1.xml.gz](https://github.com/greenbone/gsa/files/6341756/report-291071ab-8467-4034-804d-fc3add8922c1.xml.gz)
I don't see any differences. So I have no idea why I must call it twice.

**Comment by sbrun** [comment]
Hello,
I'm working on the Debian/Kali packages. I reproduce the issue when testing the Kali packages version 21.4 (packages are in kali-experimental).
When I upgrade gvm packages from version 20.8 to 21.4, the scan reports are no longer displayed in the ui and I have the same error ```e is undefined```.
Running the ```gvmd --rebuild``` command fixes this.

(of course I don't have the issue with a fresh install of gvm 21.4)

**Comment by bjoernricks** [comment]
Would it be possible to get a [har file](https://www.ghacks.net/2020/12/29/how-to-create-and-view-har-files-for-website-troubleshooting/) from opening a defect report? In that case we would be able to fix the crash in GSA at least.

**Comment by sbrun** [comment]
[gsa.zip](https://github.com/greenbone/gsa/files/6639029/gsa.zip)
Here is the har file.
Let me know if you need other information.

**Comment by bjoernricks** [comment]
Hi @sbrun I think your har file contains the results list only and not the defect report. Are you sure this file shows a defect in GSA? After a first quick look I can't find an issue in the results xml data.

**Comment by sbrun** [comment]
[screenshot-and-har.zip](https://github.com/greenbone/gsa/files/6649586/screenshot-and-har.zip)
Hi,
you're right, the har file does not seem to show the error... 
I have again generated a har file and I have taken a screenshot. And I still don't find the error in the har file. it seems likely that the error is dynamically generated and displayed.

**Comment by bjoernricks** [comment]
I've had some time now to look at the problem. IMHO it should be fixed by https://github.com/greenbone/gsa/pull/2944 released with GSA 21.4.1 last week. Could you check if the problem is gone for you too?

**Comment by sbrun** [comment]
I tested with GSA 21.4.1 and I no longer have the issue.
Thanks
