### ISSUE TITLE
Cannot change RADIUS secret

### ISSUE THREAD

**Issue by libellux** [greenbone/gsa#2862]
After upgrading to GSA 21.04 I cannot any longer change the RADIUS secret from the web interface (as admin). The authentication works using the standard  testing123 secret.

### Expected behavior

* Update to submitted secret

### Actual behavior

* Standard RADIUS secret is the value

### Steps to reproduce

1. Login as admin
2. Try enable RADIUS
3. Update the secret

### GVM versions

**gsa: 21.04**
**gvm: 21.04**
**openvas-scanner: 21.04**
**gvm-libs: 21.04**

### Environment

**Operating system:**

Linux lbx-auth01 5.4.0-70-generic #78-Ubuntu SMP Fri Mar 19 13:29:52 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source: https://www.libellux.com/openvas/**

**Comment by sarahd93** [comment]
This should already be fixed with https://github.com/greenbone/gsa/pull/2891
