### ISSUE TITLE
The elevate credential must be different from the SSH credential

### ISSUE THREAD

**Issue by BasvanH** [greenbone/gsa#3038]
### Expected behavior

Able to rename a target without credentials.
Able to create a target without credentials.

### Actual behavior

When I try to rename a target I get an error and unable to save it.
`The elevate credential must be different from the SSH credential`

I get the same error when trying to create a target without credentials.

### Steps to reproduce

I recently upgraded to v20.4.1, but unsure if this bug is due to this.

### GVM versions

Greenbone Security Assistant 21.4.1 dev1
Greenbone Vulnerability Manager 21.4.1 git-5f3063af8-HEAD
GIT revision 5f3063af8-HEAD
Manager DB revision 242
OpenVAS 21.4.1 git-81c6a4e8-HEAD
GIT revision git-81c6a4e8-HEAD
gvm-libs 21.4.1git-f10b1be1-HEAD

Please adjust the github issue template,
**openvas-scanner:** (openvassd --version)

Should be:
**openvas-scanner:** (openvas --version)

### Environment

**Operating system:**
Linux xxxxxx 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

**Comment by BasvanH** [comment]
Return from GMP:
`<envelope><version>21.4.1~dev1</version><vendor_version></vendor_version><token>381094c6-da74-4ea7-bcdb-85342488a198</token><time>Mon Jun 28 06:48:26 2021 GMT</time><timezone>UTC</timezone><login>admin</login><session>1624868278</session><role>Admin</role><i18n>nl_NL</i18n><client_address>1.1.1.1</client_address><backend_operation>0.05</backend_operation><action_result><action>Save Target</action><message>The elevate credential must be different from the SSH credential</message></action_result></envelope>`

**Comment by bjoernricks** [comment]
Thanks for your report. We are already aware of that issue and will create a fix soon.

**Comment by bjoernricks** [comment]
It is already fixed with https://github.com/greenbone/gvmd/pull/1586

**Comment by BasvanH** [comment]
Ok great, whats the eta for v21.4.2 ?

**Comment by y0urself** [comment]
We will need to release https://github.com/greenbone/gvmd again. Will give you a hint, if we are done. Expected today.

**Comment by y0urself** [comment]
@BasvanH this should be fixed with https://github.com/greenbone/gvmd/releases/tag/v21.4.2 ...

**Comment by BasvanH** [comment]
Sorry, but it isnt fixed.

```
Greenbone Vulnerability Manager 21.4.1~git-5f3063af8-HEAD
GIT revision 5f3063af8-HEAD
Manager DB revision 242
Greenbone Security Assistant 21.4.1~dev1
```

Still getting the `The elevate credential must be different from the SSH credential` when saving or adding a target without credentials.

**Comment by y0urself** [comment]
`Greenbone Vulnerability Manager 21.4.1~git-5f3063af8-HEAD` is not the correct GVMD version.
That is the commit https://github.com/greenbone/gvmd/commit/5f3063af8b9bb5f06569a8dd5914dc9b7584d11d that is tagged 21.4.1.
I have linked you the gvmd release 21.4.2. You will need to use that.

**Comment by BasvanH** [comment]
Jeesh, sorry @y0urself, I did a rebuild with v21.4.1 and not v21.4.2 . My bad, rebuilding now.

**Comment by BasvanH** [comment]
Yes, I can confirm it is solved! Much appriciated.

```
Greenbone Vulnerability Manager 21.4.2~git-09bdb532f-HEAD
GIT revision 09bdb532f-HEAD
Manager DB revision 242
```
