### ISSUE TITLE
[21.4.1] yarn offline mode fails

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#3039]
Building the app in off-line mode without internet connection using the modules package will fails with:

> [  5%] Install gsa js dependencies
> cd /builddir/build/BUILD/gsa-21.4.1/gsa && /usr/bin/yarn --offline install
> yarn install v1.22.5
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> make[2]: Leaving directory '/builddir/build/BUILD/gsa-21.4.1'
> error Can't make a request in offline mode ("https://registry.yarnpkg.com/bootstrap/-/bootstrap-4.6.0.tgz")
> make[2]: *** [gsa/CMakeFiles/gsa.dir/build.make:85: gsa/node-modules.stamp] Error 1
> make[1]: *** [CMakeFiles/Makefile2:207: gsa/CMakeFiles/gsa.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

21.4.0 will build without the error.

**Comment by bjoernricks** [comment]
This isn't possible to fix. Your yarn version and platform needs to be exactly the same as when building the node-modules tarbar. I am sorry but we can't fix this at the moment.

**Comment by bjoernricks** [comment]
Just for some background. I've tried very hard to fix this by testing several machines with different os and yarn versions. It just doesn't work reliable. take a look at the `.yarn-integrity` file in the node_modules dir.

**Comment by tuxmaster5000** [comment]
Yes this is the problem. After patching the .yarn-integrity file with sed, it will work:
`%{__sed} -i 's/linux-x64-72/linux-x64-64/g' gsa/node_modules/.yarn-integrity`
But it have no idea what 72 or 64 stands for.

**Comment by bjoernricks** [comment]
Me neither. It is really sad that this small issue hinders the usage of the offline mode. But I really can't do anything about that.

**Comment by y0urself** [comment]
x64 referes to an 64bit processor architecture (as amd64 or x86-64)

The other number may be related to the kernel version?

**Comment by tuxmaster5000** [comment]
Ah it looks like, it comes from:
https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/src/util/package-name-utils.js

**Comment by tuxmaster5000** [comment]
And this comes from : https://nodejs.org/api/process.html#process_process_versions
But I don't have the deep knowledge of node.js to get the value and set it into the file as an part of the cmake run.
