### ISSUE TITLE
[21.4.2] Node modules has other version tag

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#3106]
The nodes module package for 21.4.2 has the version number 21.4.3.
Are this an release error?
![Screenshot 2021-08-04 at 07-17-16 Release Greenbone Security Assistant (GSA) 21 4 2 · greenbone gsa](https://user-images.githubusercontent.com/837503/128126155-f4c146e5-f657-44ea-a0ef-3f679d2253e8.png)

**Comment by swaterkamp** [comment]
This was just a naming error, that'll be on my head. I renamed the files accordingly. Thanks for pointing this out.
