### ISSUE TITLE
Unable to use CMake option GSAD_PID_DIR and/or default /run/gvm for the PIDFile

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#3109]
It doesn't seem to matter if I pass the relevant CMake options

```
-DGSAD_PID_DIR:PATH=/run/gvm
-DGVM_RUN_DIR:PATH=/run/gvm
```

during build or not.

PIDFile is always created directly under `/run` instead of `/run/gvm` no matter if starting gsad as user `gvm` or `root.`

`# su -c "strace /usr/host/bin/gsad -f --listen 127.0.0.1 --port 9392 --http-only" -s /bin/bash gvm`

```
getpid()                                = 1684635
openat(AT_FDCWD, "/var/log/gvm/gsad.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 8
newfstatat(8, "", {st_mode=S_IFREG|0644, st_size=744, ...}, AT_EMPTY_PATH) = 0
write(8, "gsad main:MESSAGE:2021-08-04 09h"..., 80) = 80
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7fabc45d8f10) = 1684636
openat(AT_FDCWD, "/run/gsad.pid", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -1 EACCES (Permission denied)
getpid()                                = 1684635
write(8, "gsad main:CRITICAL:2021-08-04 09"..., 84) = 84
kill(1684636, SIGTERM)                  = 0
close(8)                                = 0
openat(AT_FDCWD, "/run/gsad.pid", O_RDONLY) = -1 ENOENT (No such file or directory)
exit_group(1)                           = ?
+++ exited with 1 +++
```

`# strace /usr/host/bin/gsad -f --listen 127.0.0.1 --port 9392 --http-only`

```
getpid()                                = 1686853
openat(AT_FDCWD, "/var/log/gvm/gsad.log", O_WRONLY|O_CREAT|O_APPEND, 0666) = 8
newfstatat(8, "", {st_mode=S_IFREG|0644, st_size=1878, ...}, AT_EMPTY_PATH) = 0
write(8, "gsad main:MESSAGE:2021-08-04 09h"..., 80) = 80
openat(AT_FDCWD, "/run/gsad.pid", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 9
getpid()                                = 1686853
newfstatat(9, "", {st_mode=S_IFREG|0644, st_size=0, ...}, AT_EMPTY_PATH) = 0
write(9, "1686853\n", 8)                = 8
close(9)                                = 0
futex(0x7f3c66283628, FUTEX_WAKE_PRIVATE, 2147483647) = 0
eventfd2(0, EFD_CLOEXEC|EFD_NONBLOCK)   = 9
socket(AF_INET, SOCK_STREAM|SOCK_CLOEXEC, IPPROTO_IP) = 10
setsockopt(10, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
bind(10, {sa_family=AF_INET, sin_port=htons(9392), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EADDRINUSE (Address already in use)
close(10)                               = 0
close(9)                                = 0
getpid()                                = 1686853
write(8, "gsad main:CRITICAL:2021-08-04 09"..., 85) = 85
close(8)                                = 0
openat(AT_FDCWD, "/run/gsad.pid", O_RDONLY) = 8
newfstatat(8, "", {st_mode=S_IFREG|0644, st_size=8, ...}, AT_EMPTY_PATH) = 0
read(8, "1686853\n", 8)                 = 8
close(8)                                = 0
getpid()                                = 1686853
unlink("/run/gsad.pid")                 = 0
exit_group(1)                           = ?
+++ exited with 1 +++
```

### Expected behavior

PID file being created under `/run/gvm/gsad.pid` or whatever desired path I pass via the relevant CMake configure option.

### Actual behavior / Steps to reproduce

PID file always being created under `/run/gsad.pid`.

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.2
**gvm:** Greenbone Vulnerability Manager 21.4.2 / Manager DB revision 242
**openvas-scanner:** OpenVAS 21.4.1
**gvm-libs:** gvm-libs 21.4.1

### Environment

**Operating system:** `Linux exherbo 5.12.0 #1 SMP Thu Apr 29 14:22:53 CEST 2021 x86_64 GNU/Linux`
**Installation method / source:** Exherbo packages (source-based)

### Logfiles
gsad.log: 
```
gsad main:MESSAGE:2021-08-04 09h04.00 utc:1684179: Starting GSAD version 21.4.2
gsad main:CRITICAL:2021-08-04 09h04.00 utc:1684180: main: Could not write PID file.
gsad main:CRITICAL:2021-08-04 09h04.00 utc:1684179: main: Could not write PID file.
```

**Comment by y0urself** [comment]
This is probably a result of https://github.com/greenbone/gsa/issues/3112, correct?

**Comment by cfi-gb** [comment]
The following works for me (`$GVM_PREFIX` is set to `/opt/gvm`) and is placing the pid file into `/opt/gvm/var/run/gsad.pid`:

```
cmake .. -DCMAKE_INSTALL_PREFIX="$GVM_PREFIX/" -DCMAKE_BUILD_TYPE=RELEASE -DSYSCONFDIR="$GVM_PREFIX/etc" -DLOCALSTATEDIR="$GVM_PREFIX/var" -DGVM_RUN_DIR="$GVM_PREFIX/var/run" -DSYSTEMD_SERVICE_DIR="$GVM_PREFIX/lib/systemd/system"
```

**Comment by bjoernricks** [comment]
Actually the path for the pid file is specified when building gvm-libs which can be adjusted with -DGVM_PID_DIR and (https://github.com/greenbone/gvm-libs/blob/master/base/pidfile.c#L55) defaults to $INSTALL_PREFIX/var/run at the moment

**Comment by tgurr** [comment]
> Actually the path for the pid file is specified when building gvm-libs which can be adjusted with -DGVM_PID_DIR and (https://github.com/greenbone/gvm-libs/blob/master/base/pidfile.c#L55) defaults to $INSTALL_PREFIX/var/run at the moment

Thanks, that worked! I had already manually set that, but (still) to /run. Confusing to have build options (GSAD_PID_DIR) which don't do what you think they're supposed to do but anyways thanks to your explanation I got around the problem and fixed our packages accordingly and can probably also get rid of a relevant manual workaround I shipped for gvmd. Thanks!

**Comment by bjoernricks** [comment]
> Thanks, that worked! I had already manually set that, but (still) to /run. Confusing to have build options (GSAD_PID_DIR) which don't do what you think they're supposed to do but anyways thanks to your explanation I got around the problem and fixed our packages accordingly and can probably also get rid of a relevant manual workaround I shipped for gvmd. Thanks!

Sorry for that. I wasn't aware that the pid file is set in gvm-libs. Just found that code. We will change that. Thanks for your issue reports otherwise we maybe never got aware of this culprit.
