### ISSUE TITLE
Nonexistent/Unset PIDFile variable used in gsad.service.in

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#3112]
https://github.com/greenbone/gsa/commit/d0f5506e4fef41448879e2489ed9839cb508dbdf part of https://github.com/greenbone/gsa/pull/3045 changed

```
-PIDFile=${GVM_RUN_DIR}/gsad.pid
+PIDFile=${GVM_PID_DIR}/gsad.pid
```

While there are CMake options for `GVM_RUN_DIR` and `GSAD_PID_DIR` the variable `GVM_PID_DIR` now used in `gsad.service.in` doesn't seem to exist elsewhere in the entire codebase resulting in the actual service file reading

`PIDFile=/gsad.pid`

### Expected behavior

Being able to set the variable. It should probably use `GSAD_PID_DIR` instead.

### Actual behavior / Steps to reproduce

Not being able to set the variable.

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.2
**gvm:** Greenbone Vulnerability Manager 21.4.2 / Manager DB revision 242
**openvas-scanner:** OpenVAS 21.4.1
**gvm-libs:** gvm-libs 21.4.1

### Environment

**Operating system:** `Linux exherbo 5.12.0 #1 SMP Thu Apr 29 14:22:53 CEST 2021 x86_64 GNU/Linux`
**Installation method / source:** Exherbo packages (source-based)

**Comment by bjoernricks** [comment]
Fixed with #3113
