### ISSUE TITLE
Duplicated After= lines/content in gsad.service.in

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#3116]
https://github.com/greenbone/gsa/pull/3045/commits/2b267848166fd7ff7f5ee634f3140b80cba7fc38 part of https://github.com/greenbone/gsa/pull/3045 added an additional `After=` entry

```
After=network.target gvmd.service
```
which now duplicates the content from the `After=` entry that was already existing before and still is

```
After=network.target networking.service gvmd.service
```

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.2
**gvm:** Greenbone Vulnerability Manager 21.4.2 / Manager DB revision 242
**openvas-scanner:** OpenVAS 21.4.1
**gvm-libs:** gvm-libs 21.4.1

### Environment

**Operating system:** `Linux exherbo 5.12.0 #1 SMP Thu Apr 29 14:22:53 CEST 2021 x86_64 GNU/Linux`
**Installation method / source:** Exherbo packages (source-based)

**Comment by bjoernricks** [comment]
Already fixed with #3117
