### ISSUE TITLE
Token/Cookie missing or bad. Please login again.

### ISSUE THREAD

**Issue by antonisnyc94** [greenbone/gsa#3237]
Hello,

Im using gsa and Im having an issue when running the container behind an AWS application load balancer. Whenever i run the container locally im having no issues loging in, but whenever im running the container in EKS in front of an application load balancer, whenever im trying to login, im getting kicked back to the original login page without any error messages. 

Below with the images you can see that im getting authenticated correctly but then the response cookie has no values.

![Screen Shot 2021-11-12 at 8 49 47 PM](https://user-images.githubusercontent.com/36517441/141601771-baca46d9-3886-40e1-9950-445b6d233e0b.png)

![Screen Shot 2021-11-12 at 8 50 04 PM](https://user-images.githubusercontent.com/36517441/141601776-78091d84-8f98-4d05-995b-6fc40913816e.png)

![Screen Shot 2021-11-12 at 8 50 19 PM](https://user-images.githubusercontent.com/36517441/141601782-bc8e4a9f-9f17-4b8d-9848-b4a8d1024e2e.png)

Any help would be appreciated!

**Comment by cfi-gb** [comment]
@antonisnyc94 You could try the solution / suggestion provided in https://github.com/greenbone/gsad/issues/73#issuecomment-1173663620:

> You could try to send/forward the `X-Real-IP` header

Background:

Most recent systems are only configured to sent a `X-Forwarded-For` header but `gsad` (at least currently) requires / only evaluates the `X-Real-IP` header.
