### ISSUE TITLE
[21.4.4] release version reports itself as 21.4.3

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#3354]
### Expected behavior
Have the same version displayed on the about page as build/installed from.

### Actual behavior
https://github.com/greenbone/gsa/blob/d551029fec12ef59990baf6456cd33cb315d08ce/src/version.js#L19 in stable branch still reads 21.4.3 as well as version.js shipped in the 21.4.4 release tarball.

### Steps to reproduce
1. build 21.4.4 release
2. run gsad
3. see 21.4.3 instead of 21.4.4 on the about page

### GVM versions

**gsa:** Greenbone Security Assistant 21.4.4

**Comment by y0urself** [comment]
Sorry we missed to change the version in that file. Thank you for mentioning!
