### ISSUE TITLE
Failed to start greenbone-security-assistant.service: Unit greenbone-security-assistant.service not found.

### ISSUE THREAD

**Issue by dimforensics** [greenbone/gsa#3368]
After today's update of last components on Kali (sudo apt upgrade), got this error:
Failed to start greenbone-security-assistant.service: Unit greenbone-security-assistant.service not found.

**Comment by bjoernricks** [comment]
Hi,

this is clearly not an issue on our side. You can try (re-)installing GSA by running `apt install greenbone-security-assistant`. If this doesn't work it is a packaging issue and should be reported at https://bugs.kali.org/

**Comment by altjx** [comment]
@dimforensics have you found a solution for this just yet?

**Comment by bjoernricks** [comment]
Did you try to install GSA manually via `apt install greenbone-security-assistant`?

**Comment by altjx** [comment]
> Did you try to install GSA manually via `apt install greenbone-security-assistant`?

Yep. It's already installed:

```
┌──(root__cd542bd4df67)-[~]
└─# apt install greenbone-security-assistant
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
greenbone-security-assistant is already the newest version (21.4.4-0kali1).
greenbone-security-assistant set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

┌──(root__cd542bd4df67)-[~]
└─# systemctl status greenbone-security-assistant
ERROR:systemctl:Unit greenbone-security-assistant.service could not be found.
```

**Comment by altjx** [comment]
My temporary workaround was to re-create the `/usr/lib/systemd/system/greenbone-security-assistant.service` file and place the following contents in it (came from a working version):

```
[Unit]
Description=Greenbone Security Assistant (gsad)
Documentation=man:gsad(8) https://www.greenbone.net
After=network.target gvmd.service
Wants=gvmd.service

[Service]
Type=forking
User=_gvm
Group=_gvm
ExecStart=/usr/sbin/gsad --listen=127.0.0.1 --port=9392
Restart=always
TimeoutStopSec=10

[Install]
WantedBy=multi-user.target
Alias=gsad.service
```

After adding that file in the location, I can start the service, etc. Not sure why this broke all of a sudden in the latest upgrade, but this sure as hell does the trick for me!

**Comment by altjx** [comment]
FWIW: https://bugs.kali.org/view.php?id=7617

**Comment by TylerDurden2019** [comment]
Those who are having trouble starting the gsad.service after upgrading to 21.4.4-0kali4.
I suggest doing the following:

Remove the gsad service (removes other dependencies too)
> sudo apt-get remove gsad

Remove the old service file if it still exists
> rm /lib/systemd/system/greenbone-security-assistant.service

Reinstall Openvas
> sudo apt-get install openvas

Setup openvas
> sudo gvm-setup

Check the setup
> sudo gvm-check-setup

(Optional Reconfiguration) If you need to allow access via external interface
Update the file /lib/systemd/system/gsad.service replace 127.0.01 with 0.0.0.0 or another IP.
> systemctl stop gsad
> systemctl daemon-reload
> system start gsad

Everything should be back to normal now.

**Comment by marcolussetti** [comment]
For me, it seems like the issue was caused by the symlink.

ls -alh /usr/lib/systemd/system/greenbone-security-assistant.service /usr/lib/systemd/system/gsad.service

Showed that the former was a symlink to the latter.


So I did:
```bash
rm /usr/lib/systemd/system/greenbone-security-assistant.service  # Remove the symlink
mv /usr/lib/systemd/system/gsad.service /usr/lib/systemd/system/greenbone-security-assistant.service
```

And edited `/usr/lib/systemd/system/greenbone-security-assistant.service`'s last line to
`Alias=gsad.service`.

And obligatory `systemctl daemon-reload`

I suspect that you could just remove the symlink and it would work just fine after a daemon-reload?
