### ISSUE TITLE
Version incorrect for 21.4.4 tag and stable branch

### ISSUE THREAD

**Issue by pffs** [greenbone/gsa#3388]
### Expected behavior

Version should show 21.4.4 (latest release)

### Actual behavior

Version shows 21.4.3

### Steps to reproduce

1. Look in browser in the about page
2. Look in source at https://github.com/greenbone/gsa/blob/v21.4.4/src/version.js

### GVM versions

**gsa:** (gsad --version)
Greenbone Security Assistant 21.4.4

### Environment

**Operating system:**
Running in docker, though should be the same for any OS based on source

**Installation method / source:** (packages, source installation)
Installed from source 
### Logfiles

```
N/A
```

**Comment by bjoernricks** [comment]
Thanks for letting us know. I've updated the version in the stable branch. Of course the release 21.4.4 stays as it is sadly.
