### ISSUE TITLE
Feature request: Ability to set custom text in GSA title bar

### ISSUE THREAD

**Issue by MitchDrage** [greenbone/gsa#3729]
### Expected behavior

I'd like the ability to set a custom message on the title bar across the top of the webpage after login.
This message could be used for setting a system name, message of the day, system ownership, etc.
Ideally, this would be able to be passed by setting an ENV var in the community container deployment.

### Actual behavior

I have a number of GSA instances deployed around and it can get a bit complex to figure out which one I'm logged in to.

### Steps to reproduce
N/A

### GVM versions

**gsa:** 22.04.0

**gvm:** 22.4.2

**openvas-scanner:** 22.4.5

**gvm-libs:**

### Environment

**Operating system:**

Linux olucust002 5.15.0-71-generic https://github.com/greenbone/gvmd/pull/78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"

**Installation method / source:**  Community Containers

### Logfiles
N/A

**Comment by 4D617274696E** [comment]
Thank you for the suggestion! We are currently in maintenance mode for GSA while we work on the new generation of our products, which means we have a feature freeze on the Greenbone side.

I will leave this open, please feel free to create a PR and contribute your changes, we will then consider them for inclusion!

**Comment by bjoernricks** [comment]
There is a setting that can be applied to add a specific label text called `vendorLabel`. Just try to add a `public/config.js` file with the following content and run `yarn build` afterwards.

```js
config = {
  vendorLabel: "FooBar",
}
```
