### ISSUE TITLE
[22.5.0] signature of the dist tar ball invalid?

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#3801]
It looks, like the signature is broken:
```
LANG=C gpg --verify SOURCES/gsa-dist-22.5.0.tar.gz.asc 
gpg: assuming signed data in 'SOURCES/gsa-dist-22.5.0.tar.gz'
gpg: Signature made Fri Jun 30 13:15:09 2023 CEST
gpg:                using RSA key 8AE4BE429B60A59B311C2E739823FAA60ED1E580
gpg: BAD signature from "Greenbone Community Feed integrity key" [unknown]
```

**Comment by bjoernricks** [comment]
Thanks for reporting it! Not sure how this did happen. I'll check that.

**Comment by bjoernricks** [comment]
Thanks again. You have spotted an issue with our release tooling and signing additional release files. It seems the GitHub API we used for downloading the additional release assets to create the signatures doesn't return stable data. I've fixed our tooling and uploaded new signatures.
