### ISSUE TITLE
GSA 22.5.0  user manual link correct

### ISSUE THREAD

**Issue by bwittmeyer** [greenbone/gsa#3810]
### Expected behavior
Access users manual for Security assistant help menu to display current User Manual for Greenbone.

### Actual behavior

Tried to Access users manual for Security assistant help menu and got
https://docs.greenbone.net/GSM-Manual/gos-22.05/en/index.html    404 Not Found
### Steps to reproduce

1.  start firefox  referencing URL to Greenbone security assistant install
2.  Navigate to help menu on far right of menu bar
3.  select help then  Users manual. 

### GVM versionsgsa

**gsa:** Greenbone Security Assistant 22.05.1    GSA 22.5.0/latest

**gvm:** Greenbone Vulnerability Manager 22.5.4
Manager DB revision 255

**openvas-scanner:**  OpenVAS 22.7.2

**gvm-libs:**  gvm-libs 22.6.3

### Environment

**Operating system:**

Linux rocky-greenbone 4.18.0-477.10.1.el8_8.x86_64 #1 SMP Tue May 16 11:38:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

NAME="Rocky Linux"
VERSION="8.8 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.8 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"

**Installation method / source:** (packages, source installation)   source installation.  

### Logfiles
This is a GSA  only issue so only GSAD logs are included.

GSAD log:
gsad main:MESSAGE:2023-07-19 14h30.16 utc:2677772: Starting GSAD version 22.05.1
gsad  gmp:MESSAGE:2023-07-19 14h32.06 utc:2677772: Authentication success for 'XXX' from 127.0.0.1

```
```

**Comment by bjoernricks** [comment]
Already fixed with https://github.com/greenbone/gsa/pull/3792 but still requires a new release as far as I can see.

**Comment by bwittmeyer** [comment]
Since I pull archive versions of GSA to per https://greenbone.github.io/docs/latest/22.4/source-build/index.html 
Not having archive with this fix means the issue is not resolved.  Any date set for the new release.  Any Idea when this new version may be released?

**Comment by bjoernricks** [comment]
Should be fixed with https://github.com/greenbone/gsa/releases/tag/v22.5.1
