### ISSUE TITLE
Unable to create users with gsa/gsad > 22.5.0 

### ISSUE THREAD

**Issue by immauss** [greenbone/gsa#3812]
### Expected behavior

When trying to create a user, clicking the save button creates the user. 

### Actual behavior

Clicking the save button has no effect. 

### Steps to reproduce

1.  Click "Administration -> Users"
2.  Click the new user button in the top left.
3.  Fill in the form and select a role
4.  Click the save button

### GVM versions
Versions:                                                                                                                                                       
pg_gvm=v22.5.1                                                                                                                                                  
notus_scanner=v22.5.0                                                                                                                                           
gvmd=v22.5.5                                                                                                                                                    
openvas=v22.7.3                                                                                                                                                 
openvas_smb=v22.5.3                                                                                                                                             
gvm_libs=v22.6.3                                                                                                                                                
openvas_scanner=v22.7.3                                                                                                                                         
gsad=v22.5.1                                                                                                                                                    
gsa=v22.5.0                                                                                                                                                     
ospd=v21.4.4                                                                                                                                                    
ospd_openvas=v22.5.3                                                                                                                                            
python_gvm=v23.5.1                                                                                                                                              
gvm_tools=v23.4.0                                                                                                                                               
greenbone_feed_sync=v23.7.0 

### Environment

Docker container environment as built from:
https://github.com/immauss/openvas/

Based on previous container versions, this problem seems to have started with gsa/gsad 22.5.0 

```
```

**Comment by bjoernricks** [comment]
Should be fixed with https://github.com/greenbone/gsa/releases/tag/v22.5.1
