### ISSUE TITLE
Help link URLs broken

### ISSUE THREAD

**Issue by furrnace** [greenbone/gsa#3814]
### Expected behavior

click on help: get help page in browser

### Actual behavior

click on help: get broken URL in browser

### Steps to reproduce

1. click on any help button

### GVM versions

**gsa:** 22.5.1

### Environment

**Operating system:**

official CE containers

**Installation method / source:** (packages, source installation)

containers

**Comment by cfi-gb** [comment]
If the URL has a doubled `/en/en/` included (i noticed the same recently) then this might be a regression introduced in #3792 recently.

Reference: https://forum.greenbone.net/t/ce-container-help-url-broken/15273
