### ISSUE TITLE
NG: Difference in NVT text format between /ng/results and /ng/nvts

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/gsa#390]
Running the current trunk there is a difference in the formatting of the text on the two mentioned pages (havn't checked any others so far). The screenshots below are from results of the NVT with the OID 1.3.6.1.4.1.25623.1.0.902909:

![results](https://user-images.githubusercontent.com/34644702/36138218-c2885d4c-1098-11e8-95b8-74f7d795b823.png)

![nvts](https://user-images.githubusercontent.com/34644702/36138223-c77f0346-1098-11e8-8dc1-b68689268da6.png)

**Comment by bjoernricks** [comment]
As I already mentioned several times we need some explicit format to handle such issues. If we are displaying text in html the ascii based format will **NOT** be represented at the web page 1:1.

If you have some reference which nvt fields have included ascii format please and how the format should be interpreted please send me the link.
