### ISSUE TITLE
[22.8.1] - twitching hover experience on scan report navbar

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#3914]
### Expected behavior
Smooth and non twitching like it was before.

### Actual behavior
![output](https://github.com/greenbone/gsa/assets/414984/b73ce40b-4a8b-48ad-8f60-7dc3b5519c6a)

### Steps to reproduce
1. upgrade to 22.8.1
2. open a scan report
3. hover the navigation bar

### GVM versions

**gsa:** 22.07.0

**gvm:** 23.0.1

**openvas-scanner:** 22.7.6

**gvm-libs:** 22.7.3

### Environment

**Operating system:** Linux

**Installation method / source:** packages (source based distribution)

**Comment by cfi-gb** [comment]
Seems this is handled via #3920 now
