### ISSUE TITLE
Cannot read properties of undefined (reading 'get_nvts_response') at policies.js:111:43

### ISSUE THREAD

**Issue by roman-doubrava** [greenbone/gsa#4020]
### Expected behavior
When creating or editing existing compliance policies Actions, we should get a window with the defined actions.

### Actual behavior
We get an empty window and javascript errors:
policies.js:111 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get_nvts_response') at policies.js:111:43
![image](https://github.com/greenbone/gsa/assets/148868123/559f86bf-7c65-4abe-87cb-3fd5d3c9102c)
![image](https://github.com/greenbone/gsa/assets/148868123/8075e9bc-d58d-4ed6-b45a-69a3ba018647)

### Steps to reproduce
1. Install Version 22.9.1 
2. Navigate to Resilience -> Compliance policies -> Edit Policy on any policy
3. Try to edit any action
![image](https://github.com/greenbone/gsa/assets/148868123/03b74282-e502-44ba-aff6-086bde2923f8)

### GVM versions
**gsa:** (gsad --version):  22.9.1~git
**gvm:** (gvmd --version):  23.3.0
**openvas-scanner:** (openvassd --version): 22.7.9
**gvm-libs:**: 22.8.0

### Environment
**Operating system:**
Kali GNU/Linux 2024.1 
VERSION_CODENAME=kali-rolling

**Installation method / source:**: gv-setup

### Logfiles
[gsad.log](https://github.com/greenbone/gsa/files/15218296/gsad.log)

**Comment by cfi-gb** [comment]
Probably already fixed in / via #3931 but Kali is one release behind (22.9.1) and seems to not include this yet.

**Comment by iriartmaxim** [comment]
Hi, 
It's happen to me too

![image](https://github.com/greenbone/gsa/assets/97992995/fadeffb4-2d89-4af2-87a6-f04e0d98d04d)

**Comment by cfi-gb** [comment]
@iriartmaxim Please see the previous comment, you need at least GSA version 23.0.0. e.g. on Kali still the outdated 22.9.1 is shipped:

https://pkg.kali.org/pkg/greenbone-security-assistant

**Comment by roman-doubrava** [comment]
ok thank you very much
