### ISSUE TITLE
signed tarball for gsa 7.0.3

### ISSUE THREAD

**Issue by shibumi** [greenbone/gsa#495]
Hello,
There is no signed tarball for gsa 7.0.3. Could you please add it? Thanks!

**Comment by bjoernricks** [comment]
@wiegandm could you help with this issue? @shibumi would it be enough to sign the git tag?

**Comment by shibumi** [comment]
@bjoernricks Sadly our arch linux package manager can't handle signed git tags yet. So I would prefer a signed tarball for getting the new release packaged in Arch Linux.

**Comment by wiegandm** [comment]
Signatures have been uploaded.
