### ISSUE TITLE
Invalid Request

### ISSUE THREAD

**Issue by ebakirmak** [greenbone/gsa#505]
Hi, 
I am not accessing my gsa. I get error it say "The request contained an unknown or invalid Host header. If you are trying to access GSA via its hostname or a proxy, make sure GSA is set up to allow it." 

I connected from  my browser with https://172.17.6.150:4000 to openvas. 

help me please.

**Comment by bjoernricks** [comment]
That's not something for the Issue Tracker. Please use the users mailing list for such questions: http://www.openvas.org/mail.html

See #318 for the host header changes in gsa 7.0.
