### ISSUE TITLE
Get rid of form Text component

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#64]
The component was intended to add a marging after a text. Adding margins has been improved by the introduction of the Divider components. Therefore gsa/src/html/classic/ng/src/web/components/form/text.js is completely useless now.

**Comment by swaterkamp** [comment]
So removing the Text-Component around some text has an influence on how the Dividers work. As an example:

`    <FormGroup title={_('QoD')}>
      <Divider>
        <Text>{_('must be at least')}</Text>
        <Spinner {...props}/>
      </Divider>
    </FormGroup>`

The Divider is already in place but it can't handle the {_('must be at least')}. It looks like there seems to be the need for a surrounding component. Text already is a simple <span> and replacing that with just another component wouldn't really get rid of anything. Or am I missing something here?

**Comment by bjoernricks** [comment]
The Text component is also a Layout and a ClickHandler. Both are features are also unused.
Initially before Dividers exist Text components have been intended for adding a margin before (or after I really can't remember that) the displayed text. So as a result Text components should be replaces with a Layout if an alignment is required or with a span if they are placed within a Divider.

I really don't think they are useful in their current implementation anymore.

**Comment by bjoernricks** [comment]
If we want to keep a Text component as a semantical expression for text we should move it to web/components/layout/ instead. It's no longer a form component.

**Comment by swaterkamp** [comment]
As we don't really have longer texts, except for About and Help along some other instances, the context in which `<Text>` is normally used, IMHO doesn't require such a semantic component. I'd go for replacing it with `<span>` and `<Layout>` instead.
