### ISSUE TITLE
Migrate to other CSS-in-JS library

### ISSUE THREAD

**Issue by bjoernricks** [greenbone/gsa#643]
It seems glamorous will be deprecated https://github.com/paypal/glamorous/issues/419
So we need to investigate howto migrate to another CSS-in-JS solution like https://emotion.sh/

**Comment by bjoernricks** [comment]
The other possible solution is https://github.com/styled-components/styled-components

**Comment by TejasQ** [comment]
I wrote a codemod that'll automatically migrate your codebase to emotion. Maybe it could help you? https://github.com/TejasQ/babel-plugin-glamorous-to-emotion

**Comment by bjoernricks** [comment]
Disadvantages of styled-components:
* Object API (`styled.div({...})`) is new in 3.3.0 and undocumented https://github.com/styled-components/styled-components/pull/1732
* I am not sure if returning an object with styles from a function is working as expected currently
https://github.com/styled-components/styled-components/pull/1820
* It hasn't an api to filter props => all props are put into the dom
* It's not possible to define an extra classname without using [attrs](https://www.styled-components.com/docs/basics#attaching-additional-props) or an extra component to filter these props
* Difficult to understand the codebase

Advantages:
* Great community
* Referencing of components in styles https://www.styled-components.com/docs/advanced#referring-to-other-components
* Only one package to add as dependency
* [tagged-template-literals](https://www.styled-components.com/docs/advanced#tagged-template-literals) API

**Comment by swaterkamp** [comment]
After some considerations I'd opt for styled-components over emotion. I can't get rid of the feeling that emotion will face the same fate as glamorous after a while, despite it's increasing prevalence. Styled-Components just seems to be the more stable choice and it should be able to provide everything we need one way or the other.
