### ISSUE TITLE
make base path configurable instead of hardcoded /

### ISSUE THREAD

**Issue by Fregf** [greenbone/gsa#652]
I want to use gsad behind an Apache reverse proxy, in a subdirectory of the root of a domain. This mostly works with this Apache configuration:
```
<Location /openvas>
        ProxyPass http://localhost:9392
	ProxyPassReverse http://localhost:9392
        ProxyHTMLEnable On
        ProxyHTMLURLMap /       /openvas/
	ProxyAddHeaders On
</Location>
```
However even then there are some places where ProxyHTMLURLMap fails to rewrite the path of some image resources (maybe in Javascript?). It would be useful if there were a way to define a base path in gsad itself, and that it would automatically make all resources available in that path instead of in the root directory.

**Comment by bjoernricks** [comment]
Is this about master or gsa-7.0?

**Comment by root360-AndreasUlm** [comment]
Hi,

I tried the same with openvas9 on Ubuntu 18.04 and it still is not possible to change the base-url.
It would be a nice feature to be able to configure the base-url.

The expected behaviour would be:
BASE_URL='/' => http://domain/
BASE_URL='/bla' => http://domain/bla/

Can you implement this configuration option?

Regards,
Andreas

**Comment by bjoernricks** [comment]
This won't get fixed for GSA 7 and 8 anymore. I am open for a PR to master.

**Comment by Ethnical** [comment]
Hi, 
Anyone know if this is fixed on the last release ? 
thank

**Comment by bjoernricks** [comment]
Nobody did provide a PR. Therefore it is still not supported.

**Comment by Virsacer** [comment]
This change is also included in my Docker-image:
https://hub.docker.com/r/virsacer/gvm
