### ISSUE TITLE
Merge SECINFO_FILTER_FILTER constants

### ISSUE THREAD

**Issue by swaterkamp** [greenbone/gsa#700]
At the moment we are using several constants such as NVTS_FILTER_FILTER, CVES_FILTER_FILTER and so on in the filter model.
All of the SecInfo filter types are 'type=info' so it makes sense to merge those constants and use SECINFO_FILTER_FILTER only.
For this, the constants in the model have to be changed and their usage in different displays and possibly other components has to be adjusted.

**Comment by bjoernricks** [comment]
I don't think we should remove the exports from gmp/models/filter.js but we could change it to something like
```javascript
export const NVTS_FILTER_FILTER = SECINFO_FILTERS_FILTER;
```

**Comment by swaterkamp** [comment]
With regard to probably removing types "info" and "asset", this issue becomes obsolete. Closing for now.
