### ISSUE TITLE
No updates for atomicorp repositories

### ISSUE THREAD

**Issue by shibumi** [greenbone/gsa#795]
Hello,
I didn't find a mail where I can report this. So I do it here. The atomicorp centos7 Repository for openvas is stucked on version OpenVAS Manager 7.0.2. Do you have a contact to them? if they stopped supporting it, it would be nice if you can remove the hint to their repositories on your website..

**Comment by cfi-gb** [comment]
@shibumi This is indeed the wrong repository as greenbone isn't maintaining nor providing packages. Please close here and contact atomicorp (e.g. via https://www.atomicorp.com/contact-us/ or https://forums.atomicorp.com/) about this issue and the status of their packaging.

**Comment by shibumi** [comment]
Thx

**Comment by cfi-gb** [comment]
Just remembered:

There where some posts in the #openvas IRC channel few weeks ago that the atomic repositories are just stuck with older versions because they have some building issues with the recent releases on CentOS 7.

But i think they might be able to tell you more.

**Comment by atomicturtle** [comment]
Yeah this is related to the heimdal build issues with the newer library on EL7.  For future reference the github repos are: 

https://github.com/Atomicorp/openvas 
and
https://github.com/Atomicorp/openvas-docker

**Comment by cfi-gb** [comment]
Ref: https://github.com/Atomicorp/openvas/issues/2
