### ISSUE TITLE
Feature Request: Slack Alert Method

### ISSUE THREAD

**Issue by brianclemens** [greenbone/gsa#842]
It would be really helpful if we could get Slack / Mattermost supported as a method for alerting.

**Comment by cfi-gb** [comment]
@brianclemens The actual implementation of an Alter needs to be done within the Manager so it might be required that you reopen this in https://github.com/greenbone/gvm/issues

**Comment by bjoernricks** [comment]
Because the alerts have to be implemented in gvmd I am closing this issue for now.
