### ISSUE TITLE
Openvas internal error occured: could not authenticate to daemon

### ISSUE THREAD

**Issue by le0li9ht** [greenbone/gsa#855]
Hi,

I'm using openvas9 on ubuntu 18.04 machine.

When i run some tasks i'm getting the error 
**Internal error: exec_omp_get:3113 (GSA 7.0.3)**
**An internal error occurred. Diagnostics: Could not authenticate to manager daemon.**

When i checked the logs here is the ouput:
```

md manage:WARNING:2018-08-05 11h56.00 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-08-05 11h56.10 utc:24681: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction
md manage:WARNING:2018-08-05 11h56.10 utc:24681: sqlv: sql_exec_internal failed
md manage:WARNING:2018-08-05 11h56.10 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-08-05 11h56.20 utc:24681: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction
md manage:WARNING:2018-08-05 11h56.20 utc:24681: sqlv: sql_exec_internal failed
md manage:WARNING:2018-08-05 11h56.20 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-08-05 11h56.30 utc:24681: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction

md manage:WARNING:2018-08-05 11h56.30 utc:24681: sqlv: sql_exec_internal failed
md manage:WARNING:2018-08-05 11h56.30 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-08-05 11h56.40 utc:24681: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction
md manage:WARNING:2018-08-05 11h56.40 utc:24681: sqlv: sql_exec_internal failed
md manage:WARNING:2018-08-05 11h56.40 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)
md manage:WARNING:2018-08-05 11h56.50 utc:24681: sql_exec_internal: sqlite3_step failed: cannot start a transaction within a transaction
md manage:WARNING:2018-08-05 11h56.50 utc:24681: sqlv: sql_exec_internal failed
md manage:WARNING:2018-08-05 11h56.50 utc:24681: manage_schedule: manage_update_nvti_cache error (Perhaps the db went down?)

```
I tried running the **greenbone-nvt-sync** and rebuild the openvas too.
But still i'm unable to resolve the issue.

Even I'm unable to run scheduled scans too. They are not starting automatically when the time hits. My openvas9-gsa version is  **7.0.3-3bionic**

sqlite version is **3.22.0 2018-01-22 18:45:57 0c55d179733b46d8d0ba4d88e01a25e10677046ee3da1d5b1581e86726f2alt1**

**Comment by bjoernricks** [comment]
For me it seems this is caused by an broken sqlite db. Please check your database which should be placed somewhere in /var/lib/openvas
Btw. this isn't an issue in GSA. Therefore it should have been reported at https://github.com/greenbone/gvm

**Comment by hsntgm** [comment]
I had the same issue but i realised that this is a temporary warning caused by insufficient system resources.Probably your system ram is full and writing to swap.

**Comment by dpmalyala** [comment]
Kudos hsntgm

**Comment by hktalent** [comment]
$ ps -ef|grep -E 'openvassd|openvasmd'
you can see
it is in building 
now ,waiting........
