### ISSUE TITLE
TLS failed to read from client (remote scanner)

### ISSUE THREAD

**Issue by mschiessl** [greenbone/gsa#875]
### Expected behavior
Connecting to a remote scanner (slave gvmd) listenining on an interface can be triggered by "master gvmd" running a GUI when you select the scanner within task creation.

### Current behavior
I am getting the following error on the remote scanner when i start  a scan on the master

`event target:MESSAGE:2018-08-20 18h31.31 UTC:28662: Target 81fb7e58-5e65-4174-9066-xxxxxxxxxxxx for test03 (ad5fbf1e-1042-4d20-b854-xxxxxxxxxx) has been created by remote_host  
md   
main:WARNING:2018-08-20 18h31.31 UTC:28662: read_from_client_tls: failed to read from client: The TLS connection was non-properly terminated.`

when i do a downgrade to the recommended packages (latest releases) remote scanner works, but local scanning seems to have an issue there.

Once, i also added the scanner via CLI (not GUI) had even more trouble getting that thingy to rock.

### Steps to reproduce
1. Install latest version from source on master and on remote 
2. add a remote scanner (GMP + credentials + CA Cert)
3. create a scan and try to run it on the remote scanner

You will get above error message (TLS error) on the remote.
You will need to restart gvmd to interrupt the scan an be able to delte the scan

### GVM versions
**gsa:** (gsad --version)
`Greenbone Security Assistant 8.0+beta2
GIT revision 6884548aa-master`

**gvm:** (gvmd --version)
`enbone Vulnerability Manager 8.0+beta1
GIT revision 3b8ede38-master`

**openvas-scanner:** (openvassd --version)
`OpenVAS Scanner 6.0+beta2
GIT revision 2348b7a-master`

**gvm-libs:**
latest from git 

the whole build has been re-setup from scratch today.

### Environment
debian stretch - up2date
**Installation method / source:** (packages, source installation)
source installation from git

### Logfiles

gvmd.log on remote
`event target:MESSAGE:2018-08-20 18h31.31 UTC:28662: Target 81fb7e58-5e65-4174-9066-xxxxxxxxxxxx for test03 (ad5fbf1e-1042-4d20-b854-xxxxxxxxxx) has been created by box911
md   main:WARNING:2018-08-20 18h31.31 UTC:28662: read_from_client_tls: failed to read from client: The TLS connection was non-properly terminated.`

gvmd.log on master
`Task test03 (e7b59478-6534-4873-b7a7-xxxxxxxxxxxx) has been requested to start by admin`

**Comment by bjoernricks** [comment]
This seems to be an issue with gvmd and not gsa. Could you please open an issue at https://github.com/greenbone/gvm instead?

**Comment by mschiessl** [comment]
ok, moving over to GVM - you are totally right - ;)
