### ISSUE TITLE
Incorrect progress indicator during the scans when a hostname resolves to multiple IP addresses

### ISSUE THREAD

**Issue by mm1024** [greenbone/gsa#889]
### Expected behavior
Scan progress indicator goes from 0 to 100%.

### Current behavior
Scan progress indicator goes from 0 to 200%.

### Steps to reproduce
1. Run a scan against any DNS name which resolves to 2 IPs (e.g. with A and AAAA records).
2. Watch scan progress 10%, 40%, 120%, 146%, 180%...

### GVM versions
**gsa:** (gsad --version)
Today's snapshot from github.

**gvm:** (gvmd --version)

**openvas-scanner:** (openvassd --version)

**gvm-libs:**

**openvas-smb:**

### Environment
**Operating system:**
Debian Stretch 9.

**Installation method / source:** (packages, source installation)
Source.

**Comment by bjoernricks** [comment]
The progress indicator isn't calculated in gsa nor gsad. It's included in the response from gvmd. Could you open an issue at https://github.com/greenbone/gvm instead?

**Comment by mm1024** [comment]
Reported as https://github.com/greenbone/gvm/issues/174.
Thank you.
