### ISSUE TITLE
Long passwords fail with LDAP login

### ISSUE THREAD

**Issue by mm1024** [greenbone/gsa#892]
### Expected behavior
A user is able to log in with LDAP password of any permitted length (LDIF_MAXLINE is 4096, but usually the password length is allowed up to 512 chars in OpenLDAP and up to 128 chars in Active Directory).

### Current behavior
A user has a password with 96 characters and can't login.
Password policy is not set in GVMD/GSAD.

### Steps to reproduce
1. Set up LDAP server integration.
2. Set a LDAP user password with e.g. 40 characters. Login is successful.
3. Set a LDAP user password with e.g. 96 characters. Login fails.

### GVM versions
**gsa:** (gsad --version)
Today's build from a github snapshot.

**gvm:** (gvmd --version)
Today's build from a github snapshot.

**openvas-scanner:** (openvassd --version)
Today's build from a github snapshot.

**gvm-libs:**
Today's build from a github snapshot.

**openvas-smb:**
N/A

### Environment
**Operating system:**
Debian 9 Stretch

**Installation method / source:** (packages, source installation)
Built from source.

### Logfiles

gsad.log:
```
gsad  gmp:WARNING:2018-08-29 14h51.50 UTC:22974: Authentication failure for 'hacker' from 10.2.3.4
gsad  gmp:MESSAGE:2018-08-29 14h54.13 GMT:22974: Authentication success for 'hacker' from 10.2.3.4

```

**Comment by y0urself** [comment]
I will close this issue, as it is really old. If this is still relevant in the latest version(s), feel free to reopen/recreate.
