### ISSUE TITLE
[ last git  version] hardcoded cmake

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#921]
Under gsa/CMakeLists.txt the cmake command is hard coded.
But on some platforms(for example centos 7) cmake version 3 is called cmake3.
So it will fails with:
/bin/sh: cmake: command not found

**Comment by bjoernricks** [comment]
Hi, we are not doing integrations for distribution specific features. I suppose cmake 3 is called cmake3 because cmake2 and cmake3 can be installed side by side. So you may create a cmake symlink to either cmake2 or cmake3.
