### ISSUE TITLE
gsa a0a1fc856-master bad for Ubuntu 18.04 (yarn install fails, all pages empty)

### ISSUE THREAD

**Issue by asmaack** [greenbone/gsa#944]
Last month (Aug) I did a clean install of gsa (Git revision d1a83ab88-master) on a clean Ubuntu 18.04. Following master/INSTALL.md, all went well and I had a working copy of gsa in no time.

Today I attempted an installation of an up-to-date gsa on an other, but identical system. The install breaks with a yarn error, which I could fix, but after a successful installation, gsa will start, but all gsa pages appear empty.

### Expected behavior
Smooth install on Ubuntu 18.04

### Current behavior
1) make breaks in installation with a yarn error:
```
$ make
error An unexpected error occurred: "https://registry.yarnpkg.com/@vx/text/-/text-0.0.159.tgz: unable to get local issuer certificate".
info If you think this is a bug, please open a bug report with the information provided in "/home/xxx/gsa/gsa/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
gsa/CMakeFiles/gsa-ng.dir/build.make:62: recipe for target 'gsa/node-modules.stamp' failed
make[2]: *** [gsa/node-modules.stamp] Error 1
CMakeFiles/Makefile2:87: recipe for target 'gsa/CMakeFiles/gsa-ng.dir/all' failed
make[1]: *** [gsa/CMakeFiles/gsa-ng.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```
I noticed the "unable to get local issuer certificate" so I did:

`$ yarn config set strict-ssl false`

Then, I did the installation again and all went well.

 2) I then started the gsad with the following command (domain names fake):
```
$ sudo gsad --munix-socket=/usr/local/var/run/gvmd.sock --http-cors="https://gsa.domain.com:443" --ssl-private-key=/etc/letsencrypt/live/gsa.domain.com/privkey.pem --ssl-certificate=/etc/letsencrypt/live/gsa.domain.com/fullchain.pem
```
My server will listen on http/80 and https/443 with response 200 OK and a valid cert, but all pages appear empty.

The HTML source code for the bad login page (and all pages) appears to be:

```
<!DOCTYPE html>
<html>
  <head>
   <link rel="icon" href="%PUBLIC_URL%/img/favicon.gif" type="image/gif"/>
   <title>Greenbone Security Assistant</title>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <script type="text/javascript" src="%PUBLIC_URL%/config.js"></script>
   </head>
   <body>
   <div id="app"></div>
   <div id="portals"></div>
   </body>
   </html>
```

Whereas a valid page on one of my working gsa server appears to be:

```
<!DOCTYPE html>
<html>
<head>
<link rel="icon" href="/img/favicon.gif" type="image/gif"/>
<title>Greenbone Security Assistant</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<script type="text/javascript" src="/config.js"></script>
<script type="text/javascript" src="/config.local.js"></script>
<link href="/static/css/main.4053d4d0.css" rel="stylesheet">
</head>
<body>
<div id="app"></div>
<div id="portals"></div>
<script type="text/javascript" src="/static/js/main.0e82d7ee.js"></script>
</body>
</html>
```

Now, I reset my git clone back to the one I was using in August:

```
$ git reset --hard d1a83ab88
HEAD is now at d1a83ab88 Merge pull request #870 from swaterkamp/TargetComments
```

did the installation process all over again, all went well, started gsad with the same command and my gsad was serving all pages normally.

The gsad log (/usr/local/var/log/gvm/gsad.log) was not throughing any errors at me, even with the highest log level 128 (see log file below).

### Steps to reproduce
1. Ubuntu 18.04 clean install, sudo apt-get update, sudo apt-get dist-upgrade.
2. Download gsa with "git clone" as of today, follow all steps in INSTALL.md

### GVM versions
**gsa:** (gsad --version)
GIT revision a0a1fc856-master

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta1
GIT revision 87f68835-master
Manager DB revision 195

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0+beta2
GIT revision fcbb60f-master

**gvm-libs:** (git log)
commit 3cb8af8fb8db54ec076b4d7212a0e99628c8b645 (HEAD -> master, origin/master, origin/HEAD)

**openvas-smb:**
NOT INSTALLED

### Environment
**Operating system:**
`$ uname -a
Linux xxx 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Installation method / source:** 
source installation

### Logfiles
/usr/local/var/log/gvm/gsad.log:
```
gsad main:MESSAGE:2018-09-17 11h13.05 utc:7957: Starting GSAD version 8.0+beta2 (GIT revision a0a1fc856-master)
gsad main:  DEBUG:2018-09-17 11h13.05 utc:7957: Forking...
gsad main:  DEBUG:2018-09-17 11h13.05 utc:7958: Forking for redirect...
gsad main:  DEBUG:2018-09-17 11h13.05 utc:7959: GSAD started successfully and is redirecting on port 80.
gsad main:  DEBUG:2018-09-17 11h13.05 utc:7958: GSAD started successfully and is listening on port 443.
gsad http:  DEBUG:2018-09-17 11h13.45 utc:7958: Default file successful.
gsad main:  DEBUG:2018-09-17 11h13.45 utc:7958: connectiontype=2
gsad http:  DEBUG:2018-09-17 11h13.45 utc:7958: Default file successful.
gsad main:  DEBUG:2018-09-17 11h13.45 utc:7958: connectiontype=2
gsad http:  DEBUG:2018-09-17 11h14.25 utc:7958: Default file successful.
gsad main:  DEBUG:2018-09-17 11h14.25 utc:7958: connectiontype=2
```

**Comment by bjoernricks** [comment]
Yeah I did introduce a bug which will be fixed with #946

But you should **NOT** use master in production. I may brake every day with every PR. I really can't recommend to use it on a stable system.

**Comment by asmaack** [comment]
Which branch should be used at any given time, for production systems?
Maybe having a "stable" branch would be good to have?

Anyways, I'm always happy to help.
-Á

**Comment by bjoernricks** [comment]
For details about the releases and versions see https://community.greenbone.net/t/gvm-9-stable-initial-release-2017-03-07/211

The current stable branch is https://github.com/greenbone/gsa/tree/gsa-7.0. 

gsa master is a rewrite and therefore differs a lot from gsa-7.0. It's completely fine to use master but you should not expect a stable system.
