### ISSUE TITLE
Chinese tokens in task date strings

### ISSUE THREAD

**Issue by asmaack** [greenbone/gsa#951]
### Expected behavior
Normal latin-1 chars expected in date strings for all tasks.

### Current behavior
Chinese chars are displayed in task date strings. See attachment.
![screenshot_2018-09-19 greenbone security assistant](https://user-images.githubusercontent.com/8437210/45741790-04ac2f00-bbe8-11e8-9209-66be3b550ffd.png)

Same reports/results viewed and downloaded over gvm-cli are all normal latin-1 chars in date strings and everywhere else.

### GVM versions
**gsa:** (gsad --version)
Greenbone Security Assistant 8.0+beta2
GIT revision d1a83ab88-master

**gvm:** (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta1
GIT revision 87f68835-master

**openvas-scanner:** (openvassd --version)
OpenVAS Scanner 6.0+beta2
GIT revision fcbb60f-master

**gvm-libs:**
git log:
commit 3cb8af8fb8db54ec076b4d7212a0e99628c8b645 (HEAD -> master, origin/master, origin/HEAD)

**openvas-smb:**
NOT INSTALLED

### Environment
**Operating system:**
uname -a
Linux xxx 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Installation method / source:** (packages, source installation)
source installation

**Comment by bjoernricks** [comment]
Could you check your detected locale settings by enabling the debug output in the browser console? To enable the console you should update at least to 2c7ed88f037f468efe5e7a54719a91044b391780

Open your browsers console (Ctrl+Shitf+I should work) and insert
```js
gmp.settings.loglevel = 'debug';
```
afterwards do a reload of the page and you should get something like
```
gmp.locale.detector Detected language en
gmp.locale.lang Language changed to en
gmp.locale.date Setting date locale to en
```
displayed at the browser console.

**Comment by asmaack** [comment]
I updated my gsa to newest master, with "git pull", did the build process, and started gsad again.
~$ gsad -V
Greenbone Security Assistant 8.0+beta2
GIT revision ed1735dae-master

The Chinese tokens are stilled displayed on task date strings.

Opening the browser console with Ctrl-Shift-I and inserting "gmp.settings.loglevel = 'debug';" on the command line, doing F5 and Ctrl-F5 will not show anything in the browser console. 
However opening the console with Ctrl-Shift-J will show the browser log with:

GET https://gsa.domain.com/locales/gsa-is.json    [HTTP/1.1 404 Not Found 13ms]
GET https://gsa.domain.com/locales/gsa-en.json    [HTTP/1.1 404 Not Found 12ms]

Now, doing the same thing in Chrome will show task date strings in valid latin-1, :-)
However, when I check the browser console [in Chrome] with Ctrl-Shift-I, then inserting "gmp.settings.loglevel = 'debug';" and refreshing, I get:

GET https://gsa.domain.com/locales/gsa-en-US.json 404 (Not Found)  @ catcher.js:197
GET https://gsa.domain.com/locales/gsa-en.json 404 (Not Found)  @ catcher.js:197

So, invalid chars in Firefox (on Win7) but not in Chrome (on Win7). 
Can't believe it has to do with my Firefox settings, which are normal as seen in about:preferences.

**Comment by bjoernricks** [comment]
I suppose you still have a `config.js` file in you install path. This file overrides gmp.settings.loglevel set on runtime. Could you check if the file is still installed. The path should be something with  `/usr/share/gvm/gsad/web`

Also you could try to set an explicit language at the user settings. By default the detected browser language is used for the locales. Maybe this doesn't work for you.

**Comment by bjoernricks** [comment]
In firefox the direct shortcut to the browser console is `ctrl+shift+k` but that doesn't seem to work in chrome.

**Comment by asmaack** [comment]
ok, found /usr/local/share/gvm/gsad/web/config.js and deleted it.

In Firefox console I get:
gmp.http Using http options  Object { timeout: undefined, transform: {…} } log.js:65:15
gmp.locale.detector Detected language is 
gmp.locale.lang Language changed to is
gmp.locale.date Setting date locale to is 

So, my language settings are correct, is (icelandic) which is a subset of latin-1.
Still all Chinese in date strings.

**Comment by bjoernricks** [comment]
Thanks! is isn't supported currently for date locales. We are currently only supporting languages that are selectable in the user settings dropdown list. See also https://github.com/greenbone/gsa/blob/master/gsa/src/gmp/models/date.js for included date locales.

Nevertheless this behavior is a bug because the date locale should fall back to **en** for unknown locales too.

**Comment by bjoernricks** [comment]
Could you check if #966 fixes you problem. It should set **en** as a fallback for unknown locales like **is**

**Comment by asmaack** [comment]
I choose "English" in "My Settings" and now all date strings are normal latin-1 (English).

I go back to reproduce the problem, choosing "Browser Language" (which was what I was using earlier) in My Settings, log out and in again, but date strings are still normal latin-1, and not Chinese, restarting the browser has no effect.

I did an upgrade:
```
~/gsa$ git pull
remote: Enumerating objects: 207, done.
remote: Counting objects: 100% (207/207), done.
remote: Compressing objects: 100% (71/71), done.
remote: Total 207 (delta 149), reused 191 (delta 134), pack-reused 0
Receiving objects: 100% (207/207), 29.99 KiB | 7.50 MiB/s, done.
Resolving deltas: 100% (149/149), completed with 31 local objects.
From https://github.com/greenbone/gsa
   ed1735dae..f51173b63  master     -> origin/master
Updating ed1735dae..f51173b63
Fast-forward
 .circleci/config.yml                                                  |   6 +-
 INSTALL.md                                                            |  10 +-
 gsa/CMakeLists.txt                                                    |   3 +-
 gsa/package.json                                                      |   4 +
 gsa/src/gmp/gmp.js                                                    |   2 +-
 gsa/src/gmp/locale/__tests__/lang.js                                  |  27 +-
 gsa/src/gmp/locale/__tests__/languages.js                             |  68 ++++
 gsa/src/gmp/locale/detector.js                                        |   5 +-
 gsa/src/gmp/locale/lang.js                                            |  24 +-
 gsa/src/gmp/locale/languages.js                                       |  78 +++++
 gsa/src/setupTests.js                                                 |   3 +-
 gsa/src/web/components/chart/topology.js                              |   3 +-
 gsa/src/web/components/dashboard/display/datadisplay.js               |   2 +-
 gsa/src/web/components/form/filefield.js                              |   6 +-
 gsa/src/web/components/layout/__tests__/Layout.js                     | 143 +++++++++
 gsa/src/web/components/layout/__tests__/__snapshots__/Layout.js.snap  | 529 +++++++++++++++++++++++++++++++
 .../web/components/layout/__tests__/__snapshots__/withLayout.js.snap  | 509 +++++++++++++++++++++++++++++
 gsa/src/web/components/layout/__tests__/withLayout.js                 | 157 +++++++++
 gsa/src/web/components/layout/layout.js                               |   9 +-
 gsa/src/web/components/layout/withLayout.js                           |  81 ++---
 gsa/src/web/pages/login/loginform.js                                  |  79 ++---
 gsa/src/web/pages/login/loginpage.js                                  |   2 +-
 gsa/src/web/utils/globalcss.js                                        |   2 +-
 gsa/src/web/utils/languages.js                                        |  49 +--
 gsa/yarn.lock                                                         |  45 +++
 25 files changed, 1667 insertions(+), 179 deletions(-)
 create mode 100644 gsa/src/gmp/locale/__tests__/languages.js
 create mode 100644 gsa/src/gmp/locale/languages.js
 create mode 100644 gsa/src/web/components/layout/__tests__/Layout.js
 create mode 100644 gsa/src/web/components/layout/__tests__/__snapshots__/Layout.js.snap
 create mode 100644 gsa/src/web/components/layout/__tests__/__snapshots__/withLayout.js.snap
 create mode 100644 gsa/src/web/components/layout/__tests__/withLayout.js

~/gsa$ git branch
* master
:~/gsa$ rm -r build
... build process ...
:~/gsa/build$ gsad -V
Greenbone Security Assistant 8.0+beta2
GIT revision f51173b63-master
```

The restarted gsad, logged in, all date strings are normal latin-1, even though "Browser Language" is the choosen language in "My Settings".

So, either the problem is fixed, or not reproducible in my system, or both :-)

**Comment by bjoernricks** [comment]
Thanks for confirmation :smile: 

If you turn on the debug log in the browser console you should get **en** as detected language instead of **is** now.
